/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A Category can be used to associate Objectives.
*/
export class Category {
    /**
    * A true/false boolean indicating if the Category has been archived.
    */
    'archived': boolean;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * The hex color to be displayed with the Category (for example, \"#ff0000\").
    */
    'color': string | null;
    /**
    * The name of the Category.
    */
    'name': string;
    /**
    * The Global ID of the Category.
    */
    'globalId': string;
    /**
    * The type of entity this Category is associated with; currently Milestone or Objective is the only type of Category.
    */
    'type': string;
    /**
    * The time/date that the Category was updated.
    */
    'updatedAt': Date;
    /**
    * This field can be set to another unique ID. In the case that the Category has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId': string | null;
    /**
    * The unique ID of the Category.
    */
    'id': number;
    /**
    * The time/date that the Category was created.
    */
    'createdAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": "css-color"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "globalId",
            "baseName": "global_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Category.attributeTypeMap;
    }

    public constructor() {
    }
}
