/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateCategoryParams } from '../models/CreateCategoryParams';
import { HttpFile } from '../http/http';

export class CreateMilestone {
    /**
    * The name of the Milestone.
    */
    'name': string;
    /**
    * The Milestone\'s description.
    */
    'description'?: string;
    /**
    * The workflow state that the Milestone is in.
    */
    'state'?: CreateMilestoneStateEnum;
    /**
    * A manual override for the time/date the Milestone was started.
    */
    'startedAtOverride'?: Date;
    /**
    * A manual override for the time/date the Milestone was completed.
    */
    'completedAtOverride'?: Date;
    /**
    * An array of IDs of Categories attached to the Milestone.
    */
    'categories'?: Array<CreateCategoryParams>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "CreateMilestoneStateEnum",
            "format": ""
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<CreateCategoryParams>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateMilestone.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateMilestoneStateEnum {
    InProgress = 'in progress',
    ToDo = 'to do',
    Done = 'done'
}

