/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateLabelParams } from '../models/CreateLabelParams';
import { CreateStoryCommentParams } from '../models/CreateStoryCommentParams';
import { CreateStoryLinkParams } from '../models/CreateStoryLinkParams';
import { CreateSubTaskParams } from '../models/CreateSubTaskParams';
import { CreateTaskParams } from '../models/CreateTaskParams';
import { CustomFieldValueParams } from '../models/CustomFieldValueParams';
import { HttpFile } from '../http/http';

/**
* Request parameters for creating a story.
*/
export class CreateStoryParams {
    /**
    * The description of the story.
    */
    'description'?: string;
    /**
    * Controls the story\'s archived state.
    */
    'archived'?: boolean;
    /**
    * An array of story links attached to the story.
    */
    'storyLinks'?: Array<CreateStoryLinkParams>;
    /**
    * An array of labels attached to the story.
    */
    'labels'?: Array<CreateLabelParams>;
    /**
    * The type of story (feature, bug, chore).
    */
    'storyType'?: CreateStoryParamsStoryTypeEnum;
    /**
    * A map specifying a CustomField ID and CustomFieldEnumValue ID that represents an assertion of some value for a CustomField.
    */
    'customFields'?: Array<CustomFieldValueParams>;
    /**
    * One of \"first\" or \"last\". This can be used to move the given story to the first or last position in the workflow state.
    */
    'moveTo'?: CreateStoryParamsMoveToEnum;
    /**
    * An array of IDs of files attached to the story.
    */
    'fileIds'?: Set<number>;
    /**
    * Given this story was converted from a task in another story, this is the original task ID that was converted to this story.
    */
    'sourceTaskId'?: number | null;
    /**
    * A manual override for the time/date the Story was completed.
    */
    'completedAtOverride'?: Date;
    /**
    * The name of the story.
    */
    'name': string;
    /**
    * An array of comments to add to the story.
    */
    'comments'?: Array<CreateStoryCommentParams>;
    /**
    * The ID of the epic the story belongs to.
    */
    'epicId'?: number | null;
    /**
    * The id of the story template used to create this story, if applicable. This is just an association; no content from the story template is inherited by the story simply by setting this field.
    */
    'storyTemplateId'?: string | null;
    /**
    * An array of External Links associated with this story.
    */
    'externalLinks'?: Array<string>;
    /**
    * An array of sub tasks to create.
    */
    'subTasks'?: Array<CreateSubTaskParams>;
    /**
    * The ID of the member that requested the story.
    */
    'requestedById'?: string;
    /**
    * The ID of the iteration the story belongs to.
    */
    'iterationId'?: number | null;
    /**
    * An array of tasks connected to the story.
    */
    'tasks'?: Array<CreateTaskParams>;
    /**
    * A manual override for the time/date the Story was started.
    */
    'startedAtOverride'?: Date;
    /**
    * The id of the group to associate with this story.
    */
    'groupId'?: string | null;
    /**
    * The ID of the workflow state the story will be in.
    */
    'workflowStateId'?: number;
    /**
    * The time/date the Story was updated.
    */
    'updatedAt'?: Date;
    /**
    * An array of UUIDs of the followers of this story.
    */
    'followerIds'?: Set<string>;
    /**
    * An array of UUIDs of the owners of this story.
    */
    'ownerIds'?: Set<string>;
    /**
    * This field can be set to another unique ID. In the case that the Story has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId'?: string;
    /**
    * The numeric point estimate of the story. Can also be null, which means unestimated.
    */
    'estimate'?: number | null;
    /**
    * The ID of the project the story belongs to.
    */
    'projectId'?: number | null;
    /**
    * An array of IDs of linked files attached to the story.
    */
    'linkedFileIds'?: Set<number>;
    /**
    * The due date of the story.
    */
    'deadline'?: Date | null;
    /**
    * The time/date the Story was created.
    */
    'createdAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "storyLinks",
            "baseName": "story_links",
            "type": "Array<CreateStoryLinkParams>",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<CreateLabelParams>",
            "format": ""
        },
        {
            "name": "storyType",
            "baseName": "story_type",
            "type": "CreateStoryParamsStoryTypeEnum",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "Array<CustomFieldValueParams>",
            "format": ""
        },
        {
            "name": "moveTo",
            "baseName": "move_to",
            "type": "CreateStoryParamsMoveToEnum",
            "format": ""
        },
        {
            "name": "fileIds",
            "baseName": "file_ids",
            "type": "Set<number>",
            "format": "int64"
        },
        {
            "name": "sourceTaskId",
            "baseName": "source_task_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "Array<CreateStoryCommentParams>",
            "format": ""
        },
        {
            "name": "epicId",
            "baseName": "epic_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "storyTemplateId",
            "baseName": "story_template_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "externalLinks",
            "baseName": "external_links",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "subTasks",
            "baseName": "sub_tasks",
            "type": "Array<CreateSubTaskParams>",
            "format": ""
        },
        {
            "name": "requestedById",
            "baseName": "requested_by_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "iterationId",
            "baseName": "iteration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<CreateTaskParams>",
            "format": ""
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "workflowStateId",
            "baseName": "workflow_state_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Set<string>",
            "format": "uuid"
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Set<string>",
            "format": "uuid"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "estimate",
            "baseName": "estimate",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "projectId",
            "baseName": "project_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "linkedFileIds",
            "baseName": "linked_file_ids",
            "type": "Set<number>",
            "format": "int64"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CreateStoryParams.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateStoryParamsStoryTypeEnum {
    Feature = 'feature',
    Chore = 'chore',
    Bug = 'bug'
}
export enum CreateStoryParamsMoveToEnum {
    Last = 'last',
    First = 'first'
}

