/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateLabelParams } from '../models/CreateLabelParams';
import { HttpFile } from '../http/http';

export class CreateEpic {
    /**
    * The Epic\'s description.
    */
    'description'?: string;
    /**
    * An array of Labels attached to the Epic.
    */
    'labels'?: Array<CreateLabelParams>;
    /**
    * A manual override for the time/date the Epic was completed.
    */
    'completedAtOverride'?: Date;
    /**
    * An array of IDs for Objectives to which this Epic is related.
    */
    'objectiveIds'?: Array<number>;
    /**
    * The Epic\'s name.
    */
    'name': string;
    /**
    * The Epic\'s planned start date.
    */
    'plannedStartDate'?: Date | null;
    /**
    * `Deprecated` The Epic\'s state (to do, in progress, or done); will be ignored when `epic_state_id` is set.
    */
    'state'?: CreateEpicStateEnum;
    /**
    * `Deprecated` The ID of the Milestone this Epic is related to. Use `objective_ids`.
    */
    'milestoneId'?: number | null;
    /**
    * The ID of the member that requested the epic.
    */
    'requestedById'?: string;
    /**
    * The ID of the Epic State.
    */
    'epicStateId'?: number;
    /**
    * A manual override for the time/date the Epic was started.
    */
    'startedAtOverride'?: Date;
    /**
    * `Deprecated` The ID of the group to associate with the epic. Use `group_ids`.
    */
    'groupId'?: string | null;
    /**
    * Defaults to the time/date it is created but can be set to reflect another date.
    */
    'updatedAt'?: Date;
    /**
    * An array of UUIDs for any Members you want to add as Followers on this new Epic.
    */
    'followerIds'?: Array<string>;
    /**
    * An array of UUIDS for Groups to which this Epic is related.
    */
    'groupIds'?: Array<string>;
    /**
    * An array of UUIDs for any members you want to add as Owners on this new Epic.
    */
    'ownerIds'?: Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the Epic has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId'?: string;
    /**
    * The Epic\'s deadline.
    */
    'deadline'?: Date | null;
    /**
    * Defaults to the time/date it is created but can be set to reflect another date.
    */
    'createdAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<CreateLabelParams>",
            "format": ""
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "objectiveIds",
            "baseName": "objective_ids",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "plannedStartDate",
            "baseName": "planned_start_date",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "CreateEpicStateEnum",
            "format": ""
        },
        {
            "name": "milestoneId",
            "baseName": "milestone_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "requestedById",
            "baseName": "requested_by_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "epicStateId",
            "baseName": "epic_state_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "groupIds",
            "baseName": "group_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CreateEpic.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CreateEpicStateEnum {
    InProgress = 'in progress',
    ToDo = 'to do',
    Done = 'done'
}

