/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Error returned when Datomic tx fails due to Datomc :db.error/cas-failed error
*/
export class DataConflictError {
    'error': DataConflictErrorErrorEnum;
    /**
    * An explanatory message: \"The update failed due to a data conflict. Please refresh and try again.\"
    */
    'message': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "DataConflictErrorErrorEnum",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DataConflictError.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum DataConflictErrorErrorEnum {
    DataConflictError = 'data-conflict-error'
}

