/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EpicAssociatedGroup {
    /**
    * The Group ID of the associated group.
    */
    'groupId': string;
    /**
    * The number of stories this Group owns in the Epic.
    */
    'associatedStoriesCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "associatedStoriesCount",
            "baseName": "associated_stories_count",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return EpicAssociatedGroup.attributeTypeMap;
    }

    public constructor() {
    }
}
