/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An action representing a bulk operation within a workspace2.
*/
export class HistoryActionWorkspace2BulkUpdate {
    /**
    * The ID of the entity referenced.
    */
    'id': string;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionWorkspace2BulkUpdateActionEnum;
    /**
    * The name of the workspace2 in which the BulkUpdate occurred.
    */
    'name': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionWorkspace2BulkUpdateActionEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionWorkspace2BulkUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum HistoryActionWorkspace2BulkUpdateActionEnum {
    BulkUpdate = 'bulk-update'
}

