/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StoryHistoryChangeAddsRemovesInt } from '../models/StoryHistoryChangeAddsRemovesInt';
import { StoryHistoryChangeAddsRemovesUuid } from '../models/StoryHistoryChangeAddsRemovesUuid';
import { StoryHistoryChangeOldNewBool } from '../models/StoryHistoryChangeOldNewBool';
import { StoryHistoryChangeOldNewInt } from '../models/StoryHistoryChangeOldNewInt';
import { StoryHistoryChangeOldNewStr } from '../models/StoryHistoryChangeOldNewStr';
import { StoryHistoryChangeOldNewUuid } from '../models/StoryHistoryChangeOldNewUuid';
import { HttpFile } from '../http/http';

/**
* The changes that have occurred as a result of the action.
*/
export class HistoryChangesStory {
    'description'?: StoryHistoryChangeOldNewStr;
    'archived'?: StoryHistoryChangeOldNewBool;
    'started'?: StoryHistoryChangeOldNewBool;
    'taskIds'?: StoryHistoryChangeAddsRemovesInt;
    'mentionIds'?: StoryHistoryChangeAddsRemovesUuid;
    'storyType'?: StoryHistoryChangeOldNewStr;
    'name'?: StoryHistoryChangeOldNewStr;
    'completed'?: StoryHistoryChangeOldNewBool;
    'blocker'?: StoryHistoryChangeOldNewBool;
    'epicId'?: StoryHistoryChangeOldNewInt;
    'branchIds'?: StoryHistoryChangeAddsRemovesInt;
    'commitIds'?: StoryHistoryChangeAddsRemovesInt;
    'requestedById'?: StoryHistoryChangeOldNewUuid;
    'iterationId'?: StoryHistoryChangeOldNewInt;
    'labelIds'?: StoryHistoryChangeAddsRemovesInt;
    'groupId'?: StoryHistoryChangeOldNewUuid;
    'workflowStateId'?: StoryHistoryChangeOldNewInt;
    'objectStoryLinkIds'?: StoryHistoryChangeAddsRemovesInt;
    'followerIds'?: StoryHistoryChangeAddsRemovesUuid;
    'ownerIds'?: StoryHistoryChangeAddsRemovesUuid;
    'customFieldValueIds'?: StoryHistoryChangeAddsRemovesUuid;
    'estimate'?: StoryHistoryChangeOldNewInt;
    'subjectStoryLinkIds'?: StoryHistoryChangeAddsRemovesInt;
    'blocked'?: StoryHistoryChangeOldNewBool;
    'projectId'?: StoryHistoryChangeOldNewInt;
    'deadline'?: StoryHistoryChangeOldNewStr;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "StoryHistoryChangeOldNewStr",
            "format": ""
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "StoryHistoryChangeOldNewBool",
            "format": ""
        },
        {
            "name": "started",
            "baseName": "started",
            "type": "StoryHistoryChangeOldNewBool",
            "format": ""
        },
        {
            "name": "taskIds",
            "baseName": "task_ids",
            "type": "StoryHistoryChangeAddsRemovesInt",
            "format": ""
        },
        {
            "name": "mentionIds",
            "baseName": "mention_ids",
            "type": "StoryHistoryChangeAddsRemovesUuid",
            "format": ""
        },
        {
            "name": "storyType",
            "baseName": "story_type",
            "type": "StoryHistoryChangeOldNewStr",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "StoryHistoryChangeOldNewStr",
            "format": ""
        },
        {
            "name": "completed",
            "baseName": "completed",
            "type": "StoryHistoryChangeOldNewBool",
            "format": ""
        },
        {
            "name": "blocker",
            "baseName": "blocker",
            "type": "StoryHistoryChangeOldNewBool",
            "format": ""
        },
        {
            "name": "epicId",
            "baseName": "epic_id",
            "type": "StoryHistoryChangeOldNewInt",
            "format": ""
        },
        {
            "name": "branchIds",
            "baseName": "branch_ids",
            "type": "StoryHistoryChangeAddsRemovesInt",
            "format": ""
        },
        {
            "name": "commitIds",
            "baseName": "commit_ids",
            "type": "StoryHistoryChangeAddsRemovesInt",
            "format": ""
        },
        {
            "name": "requestedById",
            "baseName": "requested_by_id",
            "type": "StoryHistoryChangeOldNewUuid",
            "format": ""
        },
        {
            "name": "iterationId",
            "baseName": "iteration_id",
            "type": "StoryHistoryChangeOldNewInt",
            "format": ""
        },
        {
            "name": "labelIds",
            "baseName": "label_ids",
            "type": "StoryHistoryChangeAddsRemovesInt",
            "format": ""
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "StoryHistoryChangeOldNewUuid",
            "format": ""
        },
        {
            "name": "workflowStateId",
            "baseName": "workflow_state_id",
            "type": "StoryHistoryChangeOldNewInt",
            "format": ""
        },
        {
            "name": "objectStoryLinkIds",
            "baseName": "object_story_link_ids",
            "type": "StoryHistoryChangeAddsRemovesInt",
            "format": ""
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "StoryHistoryChangeAddsRemovesUuid",
            "format": ""
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "StoryHistoryChangeAddsRemovesUuid",
            "format": ""
        },
        {
            "name": "customFieldValueIds",
            "baseName": "custom_field_value_ids",
            "type": "StoryHistoryChangeAddsRemovesUuid",
            "format": ""
        },
        {
            "name": "estimate",
            "baseName": "estimate",
            "type": "StoryHistoryChangeOldNewInt",
            "format": ""
        },
        {
            "name": "subjectStoryLinkIds",
            "baseName": "subject_story_link_ids",
            "type": "StoryHistoryChangeAddsRemovesInt",
            "format": ""
        },
        {
            "name": "blocked",
            "baseName": "blocked",
            "type": "StoryHistoryChangeOldNewBool",
            "format": ""
        },
        {
            "name": "projectId",
            "baseName": "project_id",
            "type": "StoryHistoryChangeOldNewInt",
            "format": ""
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "StoryHistoryChangeOldNewStr",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HistoryChangesStory.attributeTypeMap;
    }

    public constructor() {
    }
}
