/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An action representing a VCS Branch being created.
*/
export class HistoryActionBranchCreate {
    /**
    * The ID of the entity referenced.
    */
    'id': number;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The name of the VCS Branch that was pushed
    */
    'name': string;
    /**
    * The URL from the provider of the VCS Branch that was pushed
    */
    'url': string;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionBranchCreateActionEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionBranchCreateActionEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionBranchCreate.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum HistoryActionBranchCreateActionEnum {
    Create = 'create'
}

