/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IterationSlim } from '../models/IterationSlim';
import { HttpFile } from '../http/http';

/**
* The results of the Iteration search query.
*/
export class IterationSearchResults {
    /**
    * The total number of matches for the search query. The first 1000 matches can be paged through via the API.
    */
    'total': number;
    /**
    * A list of search results.
    */
    'data': Array<IterationSlim>;
    /**
    * The URL path and query string for the next page of search results.
    */
    'next': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<IterationSlim>",
            "format": ""
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IterationSearchResults.attributeTypeMap;
    }

    public constructor() {
    }
}
