/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KeyResultValue } from '../models/KeyResultValue';
import { HttpFile } from '../http/http';

export class KeyResult {
    /**
    * The ID of the Key Result.
    */
    'id': string;
    /**
    * The name of the Key Result.
    */
    'name': string;
    /**
    * The Objective to which this Key Result belongs.
    */
    'objectiveId': number;
    /**
    * The type of the Key Result (numeric, percent, or boolean).
    */
    'type': KeyResultTypeEnum;
    'initialObservedValue': KeyResultValue;
    'currentObservedValue': KeyResultValue;
    'currentTargetValue': KeyResultValue;
    /**
    * The integer percentage of progress toward completion of the Key Result.
    */
    'progress': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "objectiveId",
            "baseName": "objective_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "KeyResultTypeEnum",
            "format": ""
        },
        {
            "name": "initialObservedValue",
            "baseName": "initial_observed_value",
            "type": "KeyResultValue",
            "format": ""
        },
        {
            "name": "currentObservedValue",
            "baseName": "current_observed_value",
            "type": "KeyResultValue",
            "format": ""
        },
        {
            "name": "currentTargetValue",
            "baseName": "current_target_value",
            "type": "KeyResultValue",
            "format": ""
        },
        {
            "name": "progress",
            "baseName": "progress",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return KeyResult.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum KeyResultTypeEnum {
    Percent = 'percent',
    Boolean = 'boolean',
    Numeric = 'numeric'
}

