/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectStats } from '../models/ProjectStats';
import { HttpFile } from '../http/http';

/**
* Projects typically map to teams (such as Frontend, Backend, Mobile, Devops, etc) but can represent any open-ended product, component, or initiative.
*/
export class Project {
    /**
    * The Shortcut application url for the Project.
    */
    'appUrl': string;
    /**
    * The description of the Project.
    */
    'description': string | null;
    /**
    * True/false boolean indicating whether the Project is in an Archived state.
    */
    'archived': boolean;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * The number of days before the thermometer appears in the Story summary.
    */
    'daysToThermometer': number;
    /**
    * The color associated with the Project in the Shortcut member interface.
    */
    'color': string | null;
    /**
    * The ID of the workflow the project belongs to.
    */
    'workflowId': number;
    /**
    * The name of the Project
    */
    'name': string;
    /**
    * The Global ID of the Project.
    */
    'globalId': string;
    /**
    * The date at which the Project was started.
    */
    'startTime': Date;
    /**
    * The time/date that the Project was last updated.
    */
    'updatedAt': Date | null;
    /**
    * An array of UUIDs for any Members listed as Followers.
    */
    'followerIds': Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the Project has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId': string | null;
    /**
    * The unique ID of the Project.
    */
    'id': number;
    /**
    * Configuration to enable or disable thermometers in the Story summary.
    */
    'showThermometer': boolean;
    /**
    * The ID of the team the project belongs to.
    */
    'teamId': number;
    /**
    * The number of weeks per iteration in this Project.
    */
    'iterationLength': number;
    /**
    * The Project abbreviation used in Story summaries. Should be kept to 3 characters at most.
    */
    'abbreviation': string | null;
    'stats': ProjectStats;
    /**
    * The time/date that the Project was created.
    */
    'createdAt': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appUrl",
            "baseName": "app_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "daysToThermometer",
            "baseName": "days_to_thermometer",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": "css-color"
        },
        {
            "name": "workflowId",
            "baseName": "workflow_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "globalId",
            "baseName": "global_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "showThermometer",
            "baseName": "show_thermometer",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "iterationLength",
            "baseName": "iteration_length",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "abbreviation",
            "baseName": "abbreviation",
            "type": "string",
            "format": ""
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "ProjectStats",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Project.attributeTypeMap;
    }

    public constructor() {
    }
}
