/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Branch } from '../models/Branch';
import { Commit } from '../models/Commit';
import { LabelSlim } from '../models/LabelSlim';
import { LinkedFile } from '../models/LinkedFile';
import { PullRequest } from '../models/PullRequest';
import { StoryComment } from '../models/StoryComment';
import { StoryCustomField } from '../models/StoryCustomField';
import { StoryStats } from '../models/StoryStats';
import { SyncedItem } from '../models/SyncedItem';
import { Task } from '../models/Task';
import { TypedStoryLink } from '../models/TypedStoryLink';
import { UploadedFile } from '../models/UploadedFile';
import { HttpFile } from '../http/http';

/**
* Stories are the standard unit of work in Shortcut and represent individual features, bugs, and chores.
*/
export class Story {
    /**
    * The Shortcut application url for the Story.
    */
    'appUrl': string;
    /**
    * The description of the story.
    */
    'description': string;
    /**
    * True if the story has been archived or not.
    */
    'archived': boolean;
    /**
    * A true/false boolean indicating if the Story has been started.
    */
    'started': boolean;
    /**
    * An array of story links attached to the Story.
    */
    'storyLinks': Array<TypedStoryLink>;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * An array of labels attached to the story.
    */
    'labels': Array<LabelSlim>;
    /**
    * `Deprecated:` use `member_mention_ids`.
    */
    'mentionIds': Array<string>;
    'syncedItem'?: SyncedItem;
    /**
    * An array of Member IDs that have been mentioned in the Story description.
    */
    'memberMentionIds': Array<string>;
    /**
    * The type of story (feature, bug, chore).
    */
    'storyType': string;
    /**
    * An array of CustomField value assertions for the story.
    */
    'customFields'?: Array<StoryCustomField>;
    /**
    * An array of linked files attached to the story.
    */
    'linkedFiles': Array<LinkedFile>;
    /**
    * The ID of the workflow the story belongs to.
    */
    'workflowId': number;
    /**
    * A manual override for the time/date the Story was completed.
    */
    'completedAtOverride': Date | null;
    /**
    * The time/date the Story was started.
    */
    'startedAt': Date | null;
    /**
    * The time/date the Story was completed.
    */
    'completedAt': Date | null;
    /**
    * The name of the story.
    */
    'name': string;
    'globalId': string;
    /**
    * A true/false boolean indicating if the Story has been completed.
    */
    'completed': boolean;
    /**
    * An array of comments attached to the story.
    */
    'comments': Array<StoryComment>;
    /**
    * A true/false boolean indicating if the Story is currently a blocker of another story.
    */
    'blocker': boolean;
    /**
    * An array of Git branches attached to the story.
    */
    'branches': Array<Branch>;
    /**
    * The ID of the epic the story belongs to.
    */
    'epicId': number | null;
    /**
    * The ID of the story template used to create this story, or null if not created using a template.
    */
    'storyTemplateId': string | null;
    /**
    * An array of external links (strings) associated with a Story
    */
    'externalLinks': Array<string>;
    /**
    * The IDs of the iteration the story belongs to.
    */
    'previousIterationIds': Array<number>;
    /**
    * The ID of the Member that requested the story.
    */
    'requestedById': string;
    /**
    * The ID of the iteration the story belongs to.
    */
    'iterationId': number | null;
    'subTaskStoryIds': Array<number>;
    /**
    * An array of tasks connected to the story.
    */
    'tasks': Array<Task>;
    /**
    * An array of label ids attached to the story.
    */
    'labelIds': Array<number>;
    /**
    * A manual override for the time/date the Story was started.
    */
    'startedAtOverride': Date | null;
    /**
    * The ID of the group associated with the story.
    */
    'groupId': string | null;
    /**
    * The ID of the workflow state the story is currently in.
    */
    'workflowStateId': number;
    /**
    * The time/date the Story was updated.
    */
    'updatedAt': Date | null;
    /**
    * An array of Pull/Merge Requests attached to the story.
    */
    'pullRequests': Array<PullRequest>;
    /**
    * An array of Group IDs that have been mentioned in the Story description.
    */
    'groupMentionIds': Array<string>;
    /**
    * An array of UUIDs for any Members listed as Followers.
    */
    'followerIds': Array<string>;
    /**
    * An array of UUIDs of the owners of this story.
    */
    'ownerIds': Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the Story has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId': string | null;
    /**
    * The unique ID of the Story.
    */
    'id': number;
    /**
    * The lead time (in seconds) of this story when complete.
    */
    'leadTime'?: number;
    'parentStoryId': number | null;
    /**
    * The numeric point estimate of the story. Can also be null, which means unestimated.
    */
    'estimate': number | null;
    /**
    * An array of commits attached to the story.
    */
    'commits': Array<Commit>;
    /**
    * An array of files attached to the story.
    */
    'files': Array<UploadedFile>;
    /**
    * A number representing the position of the story in relation to every other story in the current project.
    */
    'position': number;
    /**
    * A true/false boolean indicating if the Story is currently blocked.
    */
    'blocked': boolean;
    /**
    * The ID of the project the story belongs to.
    */
    'projectId': number | null;
    /**
    * The due date of the story.
    */
    'deadline': Date | null;
    'stats': StoryStats;
    /**
    * The cycle time (in seconds) of this story when complete.
    */
    'cycleTime'?: number;
    /**
    * The time/date the Story was created.
    */
    'createdAt': Date;
    /**
    * The time/date the Story was last changed workflow-state.
    */
    'movedAt': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appUrl",
            "baseName": "app_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "started",
            "baseName": "started",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "storyLinks",
            "baseName": "story_links",
            "type": "Array<TypedStoryLink>",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<LabelSlim>",
            "format": ""
        },
        {
            "name": "mentionIds",
            "baseName": "mention_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "syncedItem",
            "baseName": "synced_item",
            "type": "SyncedItem",
            "format": ""
        },
        {
            "name": "memberMentionIds",
            "baseName": "member_mention_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "storyType",
            "baseName": "story_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "Array<StoryCustomField>",
            "format": ""
        },
        {
            "name": "linkedFiles",
            "baseName": "linked_files",
            "type": "Array<LinkedFile>",
            "format": ""
        },
        {
            "name": "workflowId",
            "baseName": "workflow_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "startedAt",
            "baseName": "started_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "globalId",
            "baseName": "global_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "completed",
            "baseName": "completed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "Array<StoryComment>",
            "format": ""
        },
        {
            "name": "blocker",
            "baseName": "blocker",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "branches",
            "baseName": "branches",
            "type": "Array<Branch>",
            "format": ""
        },
        {
            "name": "epicId",
            "baseName": "epic_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "storyTemplateId",
            "baseName": "story_template_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "externalLinks",
            "baseName": "external_links",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "previousIterationIds",
            "baseName": "previous_iteration_ids",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "requestedById",
            "baseName": "requested_by_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "iterationId",
            "baseName": "iteration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "subTaskStoryIds",
            "baseName": "sub_task_story_ids",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "tasks",
            "baseName": "tasks",
            "type": "Array<Task>",
            "format": ""
        },
        {
            "name": "labelIds",
            "baseName": "label_ids",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "workflowStateId",
            "baseName": "workflow_state_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "pullRequests",
            "baseName": "pull_requests",
            "type": "Array<PullRequest>",
            "format": ""
        },
        {
            "name": "groupMentionIds",
            "baseName": "group_mention_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "leadTime",
            "baseName": "lead_time",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "parentStoryId",
            "baseName": "parent_story_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "estimate",
            "baseName": "estimate",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "commits",
            "baseName": "commits",
            "type": "Array<Commit>",
            "format": ""
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<UploadedFile>",
            "format": ""
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "blocked",
            "baseName": "blocked",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "projectId",
            "baseName": "project_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "StoryStats",
            "format": ""
        },
        {
            "name": "cycleTime",
            "baseName": "cycle_time",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "movedAt",
            "baseName": "moved_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Story.attributeTypeMap;
    }

    public constructor() {
    }
}
