/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Emoji reaction on a comment.
*/
export class StoryReaction {
    /**
    * Emoji text of the reaction.
    */
    'emoji': string;
    /**
    * Permissions who have reacted with this.
    */
    'permissionIds': Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "emoji",
            "baseName": "emoji",
            "type": "string",
            "format": ""
        },
        {
            "name": "permissionIds",
            "baseName": "permission_ids",
            "type": "Array<string>",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return StoryReaction.attributeTypeMap;
    }

    public constructor() {
    }
}
