/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UnusableEntitlementError {
    /**
    * The tag for violating an entitlement action.
    */
    'reasonTag': UnusableEntitlementErrorReasonTagEnum;
    /**
    * Short tag describing the unusable entitlement action taken by the user.
    */
    'entitlementTag': string;
    /**
    * Message displayed to the user on why their action failed.
    */
    'message': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reasonTag",
            "baseName": "reason_tag",
            "type": "UnusableEntitlementErrorReasonTagEnum",
            "format": ""
        },
        {
            "name": "entitlementTag",
            "baseName": "entitlement_tag",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UnusableEntitlementError.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UnusableEntitlementErrorReasonTagEnum {
    EntitlementViolation = 'entitlement-violation'
}

