/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateCategoryParams } from '../models/CreateCategoryParams';
import { HttpFile } from '../http/http';

export class UpdateMilestone {
    /**
    * The Milestone\'s description.
    */
    'description'?: string;
    /**
    * A boolean indicating whether the Milestone is archived or not
    */
    'archived'?: boolean;
    /**
    * A manual override for the time/date the Milestone was completed.
    */
    'completedAtOverride'?: Date | null;
    /**
    * The name of the Milestone.
    */
    'name'?: string;
    /**
    * The workflow state that the Milestone is in.
    */
    'state'?: UpdateMilestoneStateEnum;
    /**
    * A manual override for the time/date the Milestone was started.
    */
    'startedAtOverride'?: Date | null;
    /**
    * An array of IDs of Categories attached to the Milestone.
    */
    'categories'?: Array<CreateCategoryParams>;
    /**
    * The ID of the Milestone we want to move this Milestone before.
    */
    'beforeId'?: number;
    /**
    * The ID of the Milestone we want to move this Milestone after.
    */
    'afterId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "UpdateMilestoneStateEnum",
            "format": ""
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<CreateCategoryParams>",
            "format": ""
        },
        {
            "name": "beforeId",
            "baseName": "before_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "afterId",
            "baseName": "after_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return UpdateMilestone.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UpdateMilestoneStateEnum {
    InProgress = 'in progress',
    ToDo = 'to do',
    Done = 'done'
}

