/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateLabelParams } from '../models/CreateLabelParams';
import { CustomFieldValueParams } from '../models/CustomFieldValueParams';
import { HttpFile } from '../http/http';

export class UpdateStory {
    /**
    * The description of the story.
    */
    'description'?: string;
    /**
    * True if the story is archived, otherwise false.
    */
    'archived'?: boolean;
    /**
    * An array of labels attached to the story.
    */
    'labels'?: Array<CreateLabelParams>;
    /**
    * An array of IDs of Pull/Merge Requests attached to the story.
    */
    'pullRequestIds'?: Set<number>;
    /**
    * The type of story (feature, bug, chore).
    */
    'storyType'?: UpdateStoryStoryTypeEnum;
    /**
    * A map specifying a CustomField ID and CustomFieldEnumValue ID that represents an assertion of some value for a CustomField.
    */
    'customFields'?: Array<CustomFieldValueParams>;
    /**
    * One of \"first\" or \"last\". This can be used to move the given story to the first or last position in the workflow state.
    */
    'moveTo'?: UpdateStoryMoveToEnum;
    /**
    * An array of IDs of files attached to the story.
    */
    'fileIds'?: Set<number>;
    /**
    * A manual override for the time/date the Story was completed.
    */
    'completedAtOverride'?: Date | null;
    /**
    * The title of the story.
    */
    'name'?: string;
    /**
    * The ID of the epic the story belongs to.
    */
    'epicId'?: number | null;
    /**
    * An array of External Links associated with this story.
    */
    'externalLinks'?: Array<string>;
    /**
    * An array of IDs of Branches attached to the story.
    */
    'branchIds'?: Set<number>;
    /**
    * An array of IDs of Commits attached to the story.
    */
    'commitIds'?: Set<number>;
    /**
    * The ID of the member that requested the story.
    */
    'requestedById'?: string;
    /**
    * The ID of the iteration the story belongs to.
    */
    'iterationId'?: number | null;
    /**
    * A manual override for the time/date the Story was started.
    */
    'startedAtOverride'?: Date | null;
    /**
    * The ID of the group to associate with this story
    */
    'groupId'?: string | null;
    /**
    * The ID of the workflow state to put the story in.
    */
    'workflowStateId'?: number;
    /**
    * An array of UUIDs of the followers of this story.
    */
    'followerIds'?: Set<string>;
    /**
    * An array of UUIDs of the owners of this story.
    */
    'ownerIds'?: Set<string>;
    /**
    * The ID of the story we want to move this story before.
    */
    'beforeId'?: number;
    /**
    * The numeric point estimate of the story. Can also be null, which means unestimated.
    */
    'estimate'?: number | null;
    /**
    * The ID of the story we want to move this story after.
    */
    'afterId'?: number;
    /**
    * The ID of the project the story belongs to.
    */
    'projectId'?: number | null;
    /**
    * An array of IDs of linked files attached to the story.
    */
    'linkedFileIds'?: Set<number>;
    /**
    * The due date of the story.
    */
    'deadline'?: Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<CreateLabelParams>",
            "format": ""
        },
        {
            "name": "pullRequestIds",
            "baseName": "pull_request_ids",
            "type": "Set<number>",
            "format": "int64"
        },
        {
            "name": "storyType",
            "baseName": "story_type",
            "type": "UpdateStoryStoryTypeEnum",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "custom_fields",
            "type": "Array<CustomFieldValueParams>",
            "format": ""
        },
        {
            "name": "moveTo",
            "baseName": "move_to",
            "type": "UpdateStoryMoveToEnum",
            "format": ""
        },
        {
            "name": "fileIds",
            "baseName": "file_ids",
            "type": "Set<number>",
            "format": "int64"
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "epicId",
            "baseName": "epic_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "externalLinks",
            "baseName": "external_links",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "branchIds",
            "baseName": "branch_ids",
            "type": "Set<number>",
            "format": "int64"
        },
        {
            "name": "commitIds",
            "baseName": "commit_ids",
            "type": "Set<number>",
            "format": "int64"
        },
        {
            "name": "requestedById",
            "baseName": "requested_by_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "iterationId",
            "baseName": "iteration_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "workflowStateId",
            "baseName": "workflow_state_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Set<string>",
            "format": "uuid"
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Set<string>",
            "format": "uuid"
        },
        {
            "name": "beforeId",
            "baseName": "before_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "estimate",
            "baseName": "estimate",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "afterId",
            "baseName": "after_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "projectId",
            "baseName": "project_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "linkedFileIds",
            "baseName": "linked_file_ids",
            "type": "Set<number>",
            "format": "int64"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return UpdateStory.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UpdateStoryStoryTypeEnum {
    Feature = 'feature',
    Chore = 'chore',
    Bug = 'bug'
}
export enum UpdateStoryMoveToEnum {
    Last = 'last',
    First = 'first'
}

