/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UpdateStoryContents } from '../models/UpdateStoryContents';
import { HttpFile } from '../http/http';

/**
* Request parameters for changing either a template\'s name or any of   the attributes it is designed to pre-populate.
*/
export class UpdateEntityTemplate {
    /**
    * The updated template name.
    */
    'name'?: string;
    'storyContents'?: UpdateStoryContents;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "storyContents",
            "baseName": "story_contents",
            "type": "UpdateStoryContents",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpdateEntityTemplate.attributeTypeMap;
    }

    public constructor() {
    }
}
