/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateStoryLink {
    /**
    * The type of link.
    */
    'verb'?: UpdateStoryLinkVerbEnum;
    /**
    * The ID of the subject Story.
    */
    'subjectId'?: number;
    /**
    * The ID of the object Story.
    */
    'objectId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "verb",
            "baseName": "verb",
            "type": "UpdateStoryLinkVerbEnum",
            "format": ""
        },
        {
            "name": "subjectId",
            "baseName": "subject_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "objectId",
            "baseName": "object_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return UpdateStoryLink.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum UpdateStoryLinkVerbEnum {
    Blocks = 'blocks',
    Duplicates = 'duplicates',
    RelatesTo = 'relates to'
}

