/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateTask {
    /**
    * The Task description.
    */
    'description': string;
    /**
    * True/false boolean indicating whether the Task is completed. Defaults to false.
    */
    'complete'?: boolean;
    /**
    * An array of UUIDs for any members you want to add as Owners on this new Task.
    */
    'ownerIds'?: Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the Task has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId'?: string;
    /**
    * Defaults to the time/date the Task is created but can be set to reflect another creation time/date.
    */
    'createdAt'?: Date;
    /**
    * Defaults to the time/date the Task is created in Shortcut but can be set to reflect another time/date.
    */
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "complete",
            "baseName": "complete",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CreateTask.attributeTypeMap;
    }

    public constructor() {
    }
}
