/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Request parameters for creating a Comment on a Shortcut Story.
*/
export class CreateStoryCommentParams {
    /**
    * The comment text.
    */
    'text': string;
    /**
    * The Member ID of the Comment\'s author. Defaults to the user identified by the API token.
    */
    'authorId'?: string;
    /**
    * Defaults to the time/date the comment is created, but can be set to reflect another date.
    */
    'createdAt'?: Date;
    /**
    * Defaults to the time/date the comment is last updated, but can be set to reflect another date.
    */
    'updatedAt'?: Date;
    /**
    * This field can be set to another unique ID. In the case that the comment has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId'?: string;
    /**
    * The ID of the Comment that this comment is threaded under.
    */
    'parentId'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "authorId",
            "baseName": "author_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentId",
            "baseName": "parent_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return CreateStoryCommentParams.attributeTypeMap;
    }

    public constructor() {
    }
}
