/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateProject {
    /**
    * The Project description.
    */
    'description'?: string;
    /**
    * The color you wish to use for the Project in the system.
    */
    'color'?: string;
    /**
    * The name of the Project.
    */
    'name': string;
    /**
    * The date at which the Project was started.
    */
    'startTime'?: Date;
    /**
    * Defaults to the time/date it is created but can be set to reflect another date.
    */
    'updatedAt'?: Date;
    /**
    * An array of UUIDs for any members you want to add as Owners on this new Epic.
    */
    'followerIds'?: Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the Project has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId'?: string;
    /**
    * The ID of the team the project belongs to.
    */
    'teamId': number;
    /**
    * The number of weeks per iteration in this Project.
    */
    'iterationLength'?: number;
    /**
    * The Project abbreviation used in Story summaries. Should be kept to 3 characters at most.
    */
    'abbreviation'?: string;
    /**
    * Defaults to the time/date it is created but can be set to reflect another date.
    */
    'createdAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": "css-color"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "iterationLength",
            "baseName": "iteration_length",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "abbreviation",
            "baseName": "abbreviation",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return CreateProject.attributeTypeMap;
    }

    public constructor() {
    }
}
