/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A references to a Story Workflow State.
*/
export class HistoryReferenceWorkflowState {
    /**
    * The ID of the entity referenced.
    */
    'id': any;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * Either \"backlog\", \"unstarted\", \"started\", or \"done\".
    */
    'type': HistoryReferenceWorkflowStateTypeEnum;
    /**
    * The name of the entity referenced.
    */
    'name': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "any",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "HistoryReferenceWorkflowStateTypeEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HistoryReferenceWorkflowState.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum HistoryReferenceWorkflowStateTypeEnum {
    Started = 'started',
    Backlog = 'backlog',
    Unstarted = 'unstarted',
    Done = 'done'
}

