/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* An action representing a Story Link being created.
*/
export class HistoryActionStoryLinkCreate {
    /**
    * The ID of the entity referenced.
    */
    'id': number;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionStoryLinkCreateActionEnum;
    /**
    * The verb describing the link\'s relationship.
    */
    'verb': HistoryActionStoryLinkCreateVerbEnum;
    /**
    * The Story ID of the subject Story.
    */
    'subjectId': number;
    /**
    * The Story ID of the object Story.
    */
    'objectId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionStoryLinkCreateActionEnum",
            "format": ""
        },
        {
            "name": "verb",
            "baseName": "verb",
            "type": "HistoryActionStoryLinkCreateVerbEnum",
            "format": ""
        },
        {
            "name": "subjectId",
            "baseName": "subject_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "objectId",
            "baseName": "object_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionStoryLinkCreate.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum HistoryActionStoryLinkCreateActionEnum {
    Create = 'create'
}
export enum HistoryActionStoryLinkCreateVerbEnum {
    Blocks = 'blocks',
    Duplicates = 'duplicates',
    RelatesTo = 'relates to'
}

