/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HistoryChangesStory } from '../models/HistoryChangesStory';
import { HttpFile } from '../http/http';

/**
* An action representing a Story being updated.
*/
export class HistoryActionStoryUpdate {
    /**
    * The ID of the entity referenced.
    */
    'id': number;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionStoryUpdateActionEnum;
    /**
    * The application URL of the Story.
    */
    'appUrl': string;
    'changes'?: HistoryChangesStory;
    /**
    * The name of the Story.
    */
    'name': string;
    /**
    * The type of Story; either feature, bug, or chore.
    */
    'storyType': HistoryActionStoryUpdateStoryTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionStoryUpdateActionEnum",
            "format": ""
        },
        {
            "name": "appUrl",
            "baseName": "app_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "changes",
            "baseName": "changes",
            "type": "HistoryChangesStory",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "storyType",
            "baseName": "story_type",
            "type": "HistoryActionStoryUpdateStoryTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionStoryUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum HistoryActionStoryUpdateActionEnum {
    Update = 'update'
}
export enum HistoryActionStoryUpdateStoryTypeEnum {
    Feature = 'feature',
    Chore = 'chore',
    Bug = 'bug'
}

