/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StoryHistoryChangeOldNewInt } from '../models/StoryHistoryChangeOldNewInt';
import { StoryHistoryChangeOldNewStr } from '../models/StoryHistoryChangeOldNewStr';
import { HttpFile } from '../http/http';

/**
* The changes that have occurred as a result of the action.
*/
export class HistoryChangesStoryLink {
    'verb'?: StoryHistoryChangeOldNewStr;
    'objectId'?: StoryHistoryChangeOldNewInt;
    'subjectId'?: StoryHistoryChangeOldNewInt;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "verb",
            "baseName": "verb",
            "type": "StoryHistoryChangeOldNewStr",
            "format": ""
        },
        {
            "name": "objectId",
            "baseName": "object_id",
            "type": "StoryHistoryChangeOldNewInt",
            "format": ""
        },
        {
            "name": "subjectId",
            "baseName": "subject_id",
            "type": "StoryHistoryChangeOldNewInt",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HistoryChangesStoryLink.attributeTypeMap;
    }

    public constructor() {
    }
}
