/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Profile } from '../models/Profile';
import { HttpFile } from '../http/http';

/**
* Details about an individual user within the Workspace.
*/
export class Member {
    /**
    * The Member\'s role in the Workspace.
    */
    'role': string;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * True/false boolean indicating whether the Member has been disabled within the Workspace.
    */
    'disabled': boolean;
    'globalId': string;
    /**
    * The user state, one of partial, full, disabled, or imported.  A partial user is disabled, has no means to log in, and is not an import user.  A full user is enabled and has a means to log in.  A disabled user is disabled and has a means to log in.  An import user is disabled, has no means to log in, and is marked as an import user.
    */
    'state': MemberStateEnum;
    /**
    * The time/date the Member was last updated.
    */
    'updatedAt': Date | null;
    /**
    * Whether this member was created as a placeholder entity.
    */
    'createdWithoutInvite': boolean;
    /**
    * The Member\'s group ids
    */
    'groupIds': Array<string>;
    /**
    * The Member\'s ID in Shortcut.
    */
    'id': string;
    'profile': Profile;
    /**
    * The time/date the Member was created.
    */
    'createdAt': Date | null;
    /**
    * The id of the member that replaces this one when merged.
    */
    'replacedBy'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "globalId",
            "baseName": "global_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "MemberStateEnum",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdWithoutInvite",
            "baseName": "created_without_invite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "groupIds",
            "baseName": "group_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "Profile",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "replacedBy",
            "baseName": "replaced_by",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return Member.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum MemberStateEnum {
    Partial = 'partial',
    Full = 'full',
    Disabled = 'disabled',
    Imported = 'imported'
}

