/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A group of calculated values for this Project.
*/
export class ProjectStats {
    /**
    * The total number of stories in this Project.
    */
    'numStories': number;
    /**
    * The total number of points in this Project.
    */
    'numPoints': number;
    /**
    * The total number of documents related to this Project
    */
    'numRelatedDocuments': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "numStories",
            "baseName": "num_stories",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "numPoints",
            "baseName": "num_points",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "numRelatedDocuments",
            "baseName": "num_related_documents",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ProjectStats.attributeTypeMap;
    }

    public constructor() {
    }
}
