/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PullRequestLabel } from '../models/PullRequestLabel';
import { HttpFile } from '../http/http';

/**
* Corresponds to a VCS Pull Request attached to a Shortcut story.
*/
export class PullRequest {
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * True/False boolean indicating whether the VCS pull request has been closed.
    */
    'closed': boolean;
    /**
    * True/False boolean indicating whether the VCS pull request has been merged.
    */
    'merged': boolean;
    /**
    * Number of lines added in the pull request, according to VCS.
    */
    'numAdded': number;
    /**
    * The ID of the branch for the particular pull request.
    */
    'branchId': number;
    /**
    * An array of Story ids that have Pull Requests that change at least one of the same lines this Pull Request changes.
    */
    'overlappingStories'?: Array<number>;
    /**
    * The pull request\'s unique number ID in VCS.
    */
    'number': number;
    /**
    * The name of the branch for the particular pull request.
    */
    'branchName': string;
    /**
    * The name of the target branch for the particular pull request.
    */
    'targetBranchName': string;
    /**
    * The number of commits on the pull request.
    */
    'numCommits': number | null;
    /**
    * The title of the pull request.
    */
    'title': string;
    /**
    * The time/date the pull request was created.
    */
    'updatedAt': Date;
    /**
    * Boolean indicating that the Pull Request has Stories that have Pull Requests that change at least one of the same lines this Pull Request changes.
    */
    'hasOverlappingStories': boolean;
    /**
    * True/False boolean indicating whether the VCS pull request is in the draft state.
    */
    'draft': boolean;
    /**
    * The unique ID associated with the pull request in Shortcut.
    */
    'id': number;
    /**
    * An array of PullRequestLabels attached to the PullRequest.
    */
    'vcsLabels'?: Array<PullRequestLabel> | null;
    /**
    * The URL for the pull request.
    */
    'url': string;
    /**
    * Number of lines removed in the pull request, according to VCS.
    */
    'numRemoved': number;
    /**
    * The status of the review for the pull request.
    */
    'reviewStatus'?: string;
    /**
    * Number of lines modified in the pull request, according to VCS.
    */
    'numModified': number | null;
    /**
    * The status of the Continuous Integration workflow for the pull request.
    */
    'buildStatus'?: string;
    /**
    * The ID of the target branch for the particular pull request.
    */
    'targetBranchId': number;
    /**
    * The ID of the repository for the particular pull request.
    */
    'repositoryId': number;
    /**
    * The time/date the pull request was created.
    */
    'createdAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "closed",
            "baseName": "closed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "merged",
            "baseName": "merged",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "numAdded",
            "baseName": "num_added",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "branchId",
            "baseName": "branch_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "overlappingStories",
            "baseName": "overlapping_stories",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "branchName",
            "baseName": "branch_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetBranchName",
            "baseName": "target_branch_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "numCommits",
            "baseName": "num_commits",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "hasOverlappingStories",
            "baseName": "has_overlapping_stories",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "draft",
            "baseName": "draft",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "vcsLabels",
            "baseName": "vcs_labels",
            "type": "Array<PullRequestLabel>",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "numRemoved",
            "baseName": "num_removed",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "reviewStatus",
            "baseName": "review_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "numModified",
            "baseName": "num_modified",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "buildStatus",
            "baseName": "build_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "targetBranchId",
            "baseName": "target_branch_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "repositoryId",
            "baseName": "repository_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return PullRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
