/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Repository refers to a VCS repository.
*/
export class Repository {
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * The shorthand name of the VCS repository.
    */
    'name': string | null;
    /**
    * The VCS provider for the Repository.
    */
    'type': RepositoryTypeEnum;
    /**
    * The time/date the Repository was updated.
    */
    'updatedAt': Date | null;
    /**
    * The VCS unique identifier for the Repository.
    */
    'externalId': string | null;
    /**
    * The ID associated to the VCS repository in Shortcut.
    */
    'id': number | null;
    /**
    * The URL of the Repository.
    */
    'url': string | null;
    /**
    * The full name of the VCS repository.
    */
    'fullName': string | null;
    /**
    * The time/date the Repository was created.
    */
    'createdAt': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RepositoryTypeEnum",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "fullName",
            "baseName": "full_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Repository.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum RepositoryTypeEnum {
    Github = 'github',
    Gitlab = 'gitlab',
    Bitbucket = 'bitbucket'
}

