/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The stats object for Stories
*/
export class StoryStats {
    /**
    * The number of documents related to this Story.
    */
    'numRelatedDocuments': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "numRelatedDocuments",
            "baseName": "num_related_documents",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return StoryStats.attributeTypeMap;
    }

    public constructor() {
    }
}
