/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Task IDs that have been added or removed from the Story.
*/
export class StoryHistoryChangeAddsRemovesInt {
    /**
    * The values that have been added.
    */
    'adds'?: Array<number>;
    /**
    * The values that have been removed
    */
    'removes'?: Array<number>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "adds",
            "baseName": "adds",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "removes",
            "baseName": "removes",
            "type": "Array<number>",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return StoryHistoryChangeAddsRemovesInt.attributeTypeMap;
    }

    public constructor() {
    }
}
