/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* The Team ID for the Story.
*/
export class StoryHistoryChangeOldNewUuid {
    /**
    * The old value.
    */
    'old'?: string;
    /**
    * The new value.
    */
    '_new'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "old",
            "baseName": "old",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "_new",
            "baseName": "new",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return StoryHistoryChangeOldNewUuid.attributeTypeMap;
    }

    public constructor() {
    }
}
