/**
 * Shortcut API
 * Shortcut API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UpdateTask {
    /**
    * The Task\'s description.
    */
    'description'?: string;
    /**
    * An array of UUIDs of the owners of this story.
    */
    'ownerIds'?: Array<string>;
    /**
    * A true/false boolean indicating whether the task is complete.
    */
    'complete'?: boolean;
    /**
    * Move task before this task ID.
    */
    'beforeId'?: number;
    /**
    * Move task after this task ID.
    */
    'afterId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Array<string>",
            "format": "uuid"
        },
        {
            "name": "complete",
            "baseName": "complete",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "beforeId",
            "baseName": "before_id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "afterId",
            "baseName": "after_id",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return UpdateTask.attributeTypeMap;
    }

    public constructor() {
    }
}
