/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PullRequest } from './pullRequest';

/**
* Branch refers to a VCS branch. Branches are feature branches associated with Shortcut Stories.
*/
export class Branch {
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * A true/false boolean indicating if the Branch has been deleted.
    */
    'deleted': boolean;
    /**
    * The name of the Branch.
    */
    'name': string;
    /**
    * This field is deprecated, and will always be false.
    */
    'persistent': boolean;
    /**
    * The time/date the Branch was updated.
    */
    'updatedAt': Date | null;
    /**
    * An array of PullRequests attached to the Branch (there is usually only one).
    */
    'pullRequests': Array<PullRequest>;
    /**
    * The IDs of the Branches the Branch has been merged into.
    */
    'mergedBranchIds': Array<number>;
    /**
    * The unique ID of the Branch.
    */
    'id': number | null;
    /**
    * The URL of the Branch.
    */
    'url': string;
    /**
    * The ID of the Repository that contains the Branch.
    */
    'repositoryId': number;
    /**
    * The time/date the Branch was created.
    */
    'createdAt': Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "persistent",
            "baseName": "persistent",
            "type": "boolean"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "pullRequests",
            "baseName": "pull_requests",
            "type": "Array<PullRequest>"
        },
        {
            "name": "mergedBranchIds",
            "baseName": "merged_branch_ids",
            "type": "Array<number>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "repositoryId",
            "baseName": "repository_id",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Branch.attributeTypeMap;
    }
}

