/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateLabelParams } from './createLabelParams';

export class CreateIteration {
    /**
    * An array of UUIDs for any Members you want to add as Followers.
    */
    'followerIds'?: Array<string>;
    /**
    * An array of UUIDs for any Groups you want to add as Followers. Currently, only one Group association is presented in our web UI.
    */
    'groupIds'?: Array<string>;
    /**
    * An array of Labels attached to the Iteration.
    */
    'labels'?: Array<CreateLabelParams>;
    /**
    * The description of the Iteration.
    */
    'description'?: string;
    /**
    * The name of this Iteration.
    */
    'name': string;
    /**
    * The date this Iteration begins, e.g. 2019-07-01.
    */
    'startDate': string;
    /**
    * The date this Iteration ends, e.g. 2019-07-01.
    */
    'endDate': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Array<string>"
        },
        {
            "name": "groupIds",
            "baseName": "group_ids",
            "type": "Array<string>"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<CreateLabelParams>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "startDate",
            "baseName": "start_date",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "end_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateIteration.attributeTypeMap;
    }
}

