/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Request parameters for creating a Story Link within a Story.
*/
export class CreateStoryLinkParams {
    /**
    * The unique ID of the Story defined as subject.
    */
    'subjectId'?: number;
    /**
    * How the subject Story acts on the object Story. This can be \"blocks\", \"duplicates\", or \"relates to\".
    */
    'verb': CreateStoryLinkParams.VerbEnum;
    /**
    * The unique ID of the Story defined as object.
    */
    'objectId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subjectId",
            "baseName": "subject_id",
            "type": "number"
        },
        {
            "name": "verb",
            "baseName": "verb",
            "type": "CreateStoryLinkParams.VerbEnum"
        },
        {
            "name": "objectId",
            "baseName": "object_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateStoryLinkParams.attributeTypeMap;
    }
}

export namespace CreateStoryLinkParams {
    export enum VerbEnum {
        Blocks = <any> 'blocks',
        Duplicates = <any> 'duplicates',
        RelatesTo = <any> 'relates to'
    }
}
