/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateCategory {
    /**
    * The name of the new Category.
    */
    'name': string;
    /**
    * The hex color to be displayed with the Category (for example, \"#ff0000\").
    */
    'color'?: string;
    /**
    * This field can be set to another unique ID. In the case that the Category has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId'?: string;
    /**
    * The type of entity this Category is associated with; currently Milestone or Objective is the only type of Category.
    */
    'type'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return CreateCategory.attributeTypeMap;
    }
}

