/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateOrDeleteStoryReaction {
    /**
    * The emoji short-code to add / remove. E.g. `:thumbsup::skin-tone-4:`.
    */
    'emoji': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emoji",
            "baseName": "emoji",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateOrDeleteStoryReaction.attributeTypeMap;
    }
}

