/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateEpicComment {
    /**
    * The comment text.
    */
    'text': string;
    /**
    * The Member ID of the Comment\'s author. Defaults to the user identified by the API token.
    */
    'authorId'?: string;
    /**
    * Defaults to the time/date the comment is created, but can be set to reflect another date.
    */
    'createdAt'?: Date;
    /**
    * Defaults to the time/date the comment is last updated, but can be set to reflect another date.
    */
    'updatedAt'?: Date;
    /**
    * This field can be set to another unique ID. In the case that the comment has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "authorId",
            "baseName": "author_id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateEpicComment.attributeTypeMap;
    }
}

