/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateGroup {
    /**
    * The description of the Group.
    */
    'description'?: string;
    /**
    * The Member ids to add to this Group.
    */
    'memberIds'?: Set<string>;
    /**
    * The Workflow ids to add to the Group.
    */
    'workflowIds'?: Array<number>;
    /**
    * The name of this Group.
    */
    'name': string;
    /**
    * The mention name of this Group.
    */
    'mentionName': string;
    /**
    * The color you wish to use for the Group in the system.
    */
    'color'?: string;
    /**
    * The color key you wish to use for the Group in the system.
    */
    'colorKey'?: CreateGroup.ColorKeyEnum;
    /**
    * The Icon id for the avatar of this Group.
    */
    'displayIconId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "memberIds",
            "baseName": "member_ids",
            "type": "Set<string>"
        },
        {
            "name": "workflowIds",
            "baseName": "workflow_ids",
            "type": "Array<number>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "mentionName",
            "baseName": "mention_name",
            "type": "string"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "colorKey",
            "baseName": "color_key",
            "type": "CreateGroup.ColorKeyEnum"
        },
        {
            "name": "displayIconId",
            "baseName": "display_icon_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateGroup.attributeTypeMap;
    }
}

export namespace CreateGroup {
    export enum ColorKeyEnum {
        Blue = <any> 'blue',
        Purple = <any> 'purple',
        MidnightBlue = <any> 'midnight-blue',
        Orange = <any> 'orange',
        YellowGreen = <any> 'yellow-green',
        Brass = <any> 'brass',
        Gray = <any> 'gray',
        Fuchsia = <any> 'fuchsia',
        Yellow = <any> 'yellow',
        Pink = <any> 'pink',
        SkyBlue = <any> 'sky-blue',
        Green = <any> 'green',
        Red = <any> 'red',
        Black = <any> 'black',
        Slate = <any> 'slate',
        Turquoise = <any> 'turquoise'
    }
}
