/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CustomFieldEnumValue {
    /**
    * The unique public ID for the Custom Field.
    */
    'id': string;
    /**
    * A string value within the domain of this Custom Field.
    */
    'value': string;
    /**
    * An integer indicating the position of this Value with respect to the other CustomFieldEnumValues in the enumeration.
    */
    'position': number;
    /**
    * A color key associated with this CustomFieldEnumValue.
    */
    'colorKey': string | null;
    /**
    * A string description of this resource.
    */
    'entityType': CustomFieldEnumValue.EntityTypeEnum;
    /**
    * When true, the CustomFieldEnumValue can be selected for the CustomField.
    */
    'enabled': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "colorKey",
            "baseName": "color_key",
            "type": "string"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "CustomFieldEnumValue.EntityTypeEnum"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CustomFieldEnumValue.attributeTypeMap;
    }
}

export namespace CustomFieldEnumValue {
    export enum EntityTypeEnum {
        CustomFieldEnumValue = <any> 'custom-field-enum-value'
    }
}
