/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CustomFieldEnumValue } from './customFieldEnumValue';

export class CustomField {
    /**
    * A string description of the CustomField
    */
    'description'?: string;
    /**
    * A string that represents the icon that corresponds to this custom field.
    */
    'iconSetIdentifier'?: string;
    /**
    * A string description of this resource.
    */
    'entityType': CustomField.EntityTypeEnum;
    /**
    * The types of stories this CustomField is scoped to.
    */
    'storyTypes'?: Array<string>;
    /**
    * The name of the Custom Field.
    */
    'name': string;
    /**
    * When true, the CustomFieldEnumValues may not be reordered.
    */
    'fixedPosition'?: boolean;
    /**
    * The instant when this CustomField was last updated.
    */
    'updatedAt': Date;
    /**
    * The unique public ID for the CustomField.
    */
    'id': string;
    /**
    * A collection of legal values for a CustomField.
    */
    'values'?: Array<CustomFieldEnumValue>;
    /**
    * The type of Custom Field, eg. \'enum\'.
    */
    'fieldType': CustomField.FieldTypeEnum;
    /**
    * An integer indicating the position of this Custom Field with respect to the other CustomField
    */
    'position': number;
    /**
    * The canonical name for a Shortcut-defined field.
    */
    'canonicalName'?: string;
    /**
    * When true, the CustomField can be applied to entities in the Workspace.
    */
    'enabled': boolean;
    /**
    * The instant when this CustomField was created.
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "iconSetIdentifier",
            "baseName": "icon_set_identifier",
            "type": "string"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "CustomField.EntityTypeEnum"
        },
        {
            "name": "storyTypes",
            "baseName": "story_types",
            "type": "Array<string>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "fixedPosition",
            "baseName": "fixed_position",
            "type": "boolean"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<CustomFieldEnumValue>"
        },
        {
            "name": "fieldType",
            "baseName": "field_type",
            "type": "CustomField.FieldTypeEnum"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "canonicalName",
            "baseName": "canonical_name",
            "type": "string"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return CustomField.attributeTypeMap;
    }
}

export namespace CustomField {
    export enum EntityTypeEnum {
        CustomField = <any> 'custom-field'
    }
    export enum FieldTypeEnum {
        Enum = <any> 'enum'
    }
}
