/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Error returned when Datomic tx fails due to Datomc :db.error/cas-failed error
*/
export class DataConflictError {
    'error': DataConflictError.ErrorEnum;
    /**
    * An explanatory message: \"The update failed due to a data conflict. Please refresh and try again.\"
    */
    'message': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "DataConflictError.ErrorEnum"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DataConflictError.attributeTypeMap;
    }
}

export namespace DataConflictError {
    export enum ErrorEnum {
        DataConflictError = <any> 'data-conflict-error'
    }
}
