/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DeleteStories {
    /**
    * An array of IDs of Stories to delete.
    */
    'storyIds': Set<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "storyIds",
            "baseName": "story_ids",
            "type": "Set<number>"
        }    ];

    static getAttributeTypeMap() {
        return DeleteStories.attributeTypeMap;
    }
}

