/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Epic State is any of the at least 3 columns. Epic States correspond to one of 3 types: Unstarted, Started, or Done.
*/
export class EpicState {
    /**
    * The description of what sort of Epics belong in that Epic State.
    */
    'description': string;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * The hex color for this Epic State.
    */
    'color'?: string;
    /**
    * The Epic State\'s name.
    */
    'name': string;
    'globalId': string;
    /**
    * The type of Epic State (Unstarted, Started, or Done)
    */
    'type': string;
    /**
    * When the Epic State was last updated.
    */
    'updatedAt': Date;
    /**
    * The unique ID of the Epic State.
    */
    'id': number;
    /**
    * The position that the Epic State is in, starting with 0 at the left.
    */
    'position': number;
    /**
    * The time/date the Epic State was created.
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "globalId",
            "baseName": "global_id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return EpicState.attributeTypeMap;
    }
}

