/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EpicAssociatedGroup } from './epicAssociatedGroup';
import { EpicStats } from './epicStats';
import { LabelSlim } from './labelSlim';
import { ThreadedComment } from './threadedComment';

/**
* An Epic is a collection of stories that together might make up a release, a objective, or some other large initiative that you are working on.
*/
export class Epic {
    /**
    * The Shortcut application url for the Epic.
    */
    'appUrl': string;
    /**
    * The Epic\'s description.
    */
    'description': string;
    /**
    * True/false boolean that indicates whether the Epic is archived or not.
    */
    'archived': boolean;
    /**
    * A true/false boolean indicating if the Epic has been started.
    */
    'started': boolean;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * An array of Labels attached to the Epic.
    */
    'labels': Array<LabelSlim>;
    /**
    * `Deprecated:` use `member_mention_ids`.
    */
    'mentionIds': Array<string>;
    /**
    * An array of Member IDs that have been mentioned in the Epic description.
    */
    'memberMentionIds': Array<string>;
    /**
    * An array containing Group IDs and Group-owned story counts for the Epic\'s associated groups.
    */
    'associatedGroups': Array<EpicAssociatedGroup>;
    /**
    * The IDs of Projects related to this Epic.
    */
    'projectIds': Array<number>;
    /**
    * The number of stories in this epic which are not associated with a project.
    */
    'storiesWithoutProjects': number;
    /**
    * A manual override for the time/date the Epic was completed.
    */
    'completedAtOverride': Date | null;
    /**
    * The ID of the associated productboard integration.
    */
    'productboardPluginId': string | null;
    /**
    * The time/date the Epic was started.
    */
    'startedAt': Date | null;
    /**
    * The time/date the Epic was completed.
    */
    'completedAt': Date | null;
    /**
    * An array of IDs for Objectives to which this epic is related.
    */
    'objectiveIds': Array<number>;
    /**
    * The name of the Epic.
    */
    'name': string;
    'globalId': string;
    /**
    * A true/false boolean indicating if the Epic has been completed.
    */
    'completed': boolean;
    /**
    * A nested array of threaded comments.
    */
    'comments': Array<ThreadedComment>;
    /**
    * The URL of the associated productboard feature.
    */
    'productboardUrl': string | null;
    /**
    * The Epic\'s planned start date.
    */
    'plannedStartDate': Date | null;
    /**
    * `Deprecated` The workflow state that the Epic is in.
    */
    'state': string;
    /**
    * `Deprecated` The ID of the Objective this Epic is related to. Use `objective_ids`.
    */
    'milestoneId': number | null;
    /**
    * The ID of the Member that requested the epic.
    */
    'requestedById': string;
    /**
    * The ID of the Epic State.
    */
    'epicStateId': number;
    /**
    * An array of Label ids attached to the Epic.
    */
    'labelIds': Array<number>;
    /**
    * A manual override for the time/date the Epic was started.
    */
    'startedAtOverride': Date | null;
    /**
    * `Deprecated` The ID of the group to associate with the epic. Use `group_ids`.
    */
    'groupId': string | null;
    /**
    * The time/date the Epic was updated.
    */
    'updatedAt': Date | null;
    /**
    * An array of Group IDs that have been mentioned in the Epic description.
    */
    'groupMentionIds': Array<string>;
    /**
    * The ID of the associated productboard feature.
    */
    'productboardId': string | null;
    /**
    * An array of UUIDs for any Members you want to add as Followers on this Epic.
    */
    'followerIds': Array<string>;
    /**
    * An array of UUIDS for Groups to which this Epic is related.
    */
    'groupIds': Array<string>;
    /**
    * An array of UUIDs for any members you want to add as Owners on this new Epic.
    */
    'ownerIds': Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the Epic has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId': string | null;
    /**
    * The unique ID of the Epic.
    */
    'id': number;
    /**
    * The Epic\'s relative position in the Epic workflow state.
    */
    'position': number;
    /**
    * The name of the associated productboard feature.
    */
    'productboardName': string | null;
    /**
    * The Epic\'s deadline.
    */
    'deadline': Date | null;
    'stats': EpicStats;
    /**
    * The time/date the Epic was created.
    */
    'createdAt': Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appUrl",
            "baseName": "app_url",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "started",
            "baseName": "started",
            "type": "boolean"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<LabelSlim>"
        },
        {
            "name": "mentionIds",
            "baseName": "mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "memberMentionIds",
            "baseName": "member_mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "associatedGroups",
            "baseName": "associated_groups",
            "type": "Array<EpicAssociatedGroup>"
        },
        {
            "name": "projectIds",
            "baseName": "project_ids",
            "type": "Array<number>"
        },
        {
            "name": "storiesWithoutProjects",
            "baseName": "stories_without_projects",
            "type": "number"
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date"
        },
        {
            "name": "productboardPluginId",
            "baseName": "productboard_plugin_id",
            "type": "string"
        },
        {
            "name": "startedAt",
            "baseName": "started_at",
            "type": "Date"
        },
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "Date"
        },
        {
            "name": "objectiveIds",
            "baseName": "objective_ids",
            "type": "Array<number>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "globalId",
            "baseName": "global_id",
            "type": "string"
        },
        {
            "name": "completed",
            "baseName": "completed",
            "type": "boolean"
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "Array<ThreadedComment>"
        },
        {
            "name": "productboardUrl",
            "baseName": "productboard_url",
            "type": "string"
        },
        {
            "name": "plannedStartDate",
            "baseName": "planned_start_date",
            "type": "Date"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "milestoneId",
            "baseName": "milestone_id",
            "type": "number"
        },
        {
            "name": "requestedById",
            "baseName": "requested_by_id",
            "type": "string"
        },
        {
            "name": "epicStateId",
            "baseName": "epic_state_id",
            "type": "number"
        },
        {
            "name": "labelIds",
            "baseName": "label_ids",
            "type": "Array<number>"
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date"
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "groupMentionIds",
            "baseName": "group_mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "productboardId",
            "baseName": "productboard_id",
            "type": "string"
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Array<string>"
        },
        {
            "name": "groupIds",
            "baseName": "group_ids",
            "type": "Array<string>"
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Array<string>"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "productboardName",
            "baseName": "productboard_name",
            "type": "string"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "Date"
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "EpicStats"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Epic.attributeTypeMap;
    }
}

