/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An action representing a Story being deleted.
*/
export class HistoryActionStoryDelete {
    /**
    * The ID of the entity referenced.
    */
    'id': number;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionStoryDelete.ActionEnum;
    /**
    * The name of the Story.
    */
    'name': string;
    /**
    * The type of Story; either feature, bug, or chore.
    */
    'storyType': HistoryActionStoryDelete.StoryTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionStoryDelete.ActionEnum"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "storyType",
            "baseName": "story_type",
            "type": "HistoryActionStoryDelete.StoryTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionStoryDelete.attributeTypeMap;
    }
}

export namespace HistoryActionStoryDelete {
    export enum ActionEnum {
        Delete = <any> 'delete'
    }
    export enum StoryTypeEnum {
        Feature = <any> 'feature',
        Chore = <any> 'chore',
        Bug = <any> 'bug'
    }
}
