/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An action representing a Label being created.
*/
export class HistoryActionLabelCreate {
    /**
    * The ID of the entity referenced.
    */
    'id': number;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionLabelCreate.ActionEnum;
    /**
    * The application URL of the Label.
    */
    'appUrl': string;
    /**
    * The name of the Label.
    */
    'name': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionLabelCreate.ActionEnum"
        },
        {
            "name": "appUrl",
            "baseName": "app_url",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionLabelCreate.attributeTypeMap;
    }
}

export namespace HistoryActionLabelCreate {
    export enum ActionEnum {
        Create = <any> 'create'
    }
}
