/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A reference to a CustomField value asserted on a Story.
*/
export class HistoryReferenceCustomFieldEnumValue {
    /**
    * The ID of the entity referenced.
    */
    'id': object;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The custom-field enum value as a string.
    */
    'stringValue': string | null;
    /**
    * Whether or not the custom-field enum value is enabled.
    */
    'enumValueEnabled': boolean | null;
    /**
    * The public-id of the parent custom-field of this enum value.
    */
    'fieldId': string;
    /**
    * The type variety of the parent custom-field of this enum value.
    */
    'fieldType': string;
    /**
    * The name as it is displayed to the user of the parent custom-field of this enum value.
    */
    'fieldName': string;
    /**
    * Whether or not the custom-field is enabled.
    */
    'fieldEnabled': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "object"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "stringValue",
            "baseName": "string_value",
            "type": "string"
        },
        {
            "name": "enumValueEnabled",
            "baseName": "enum_value_enabled",
            "type": "boolean"
        },
        {
            "name": "fieldId",
            "baseName": "field_id",
            "type": "string"
        },
        {
            "name": "fieldType",
            "baseName": "field_type",
            "type": "string"
        },
        {
            "name": "fieldName",
            "baseName": "field_name",
            "type": "string"
        },
        {
            "name": "fieldEnabled",
            "baseName": "field_enabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return HistoryReferenceCustomFieldEnumValue.attributeTypeMap;
    }
}

