/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An action representing various operations for a Pull Request.
*/
export class HistoryActionPullRequest {
    /**
    * The ID of the entity referenced.
    */
    'id': number;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionPullRequest.ActionEnum;
    /**
    * The VCS Repository-specific ID for the Pull Request.
    */
    'number': number;
    /**
    * The title of the Pull Request.
    */
    'title': string;
    /**
    * The URL from the provider of the VCS Pull Request.
    */
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionPullRequest.ActionEnum"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionPullRequest.attributeTypeMap;
    }
}

export namespace HistoryActionPullRequest {
    export enum ActionEnum {
        Open = <any> 'open',
        Update = <any> 'update',
        Reopen = <any> 'reopen',
        Close = <any> 'close',
        Sync = <any> 'sync',
        Comment = <any> 'comment'
    }
}
