/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A references to a Story Workflow State.
*/
export class HistoryReferenceWorkflowState {
    /**
    * The ID of the entity referenced.
    */
    'id': object;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * Either \"backlog\", \"unstarted\", \"started\", or \"done\".
    */
    'type': HistoryReferenceWorkflowState.TypeEnum;
    /**
    * The name of the entity referenced.
    */
    'name': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "object"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "HistoryReferenceWorkflowState.TypeEnum"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HistoryReferenceWorkflowState.attributeTypeMap;
    }
}

export namespace HistoryReferenceWorkflowState {
    export enum TypeEnum {
        Started = <any> 'started',
        Backlog = <any> 'backlog',
        Unstarted = <any> 'unstarted',
        Done = <any> 'done'
    }
}
