/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An action representing a VCS Branch being pushed.
*/
export class HistoryActionBranchPush {
    /**
    * The ID of the entity referenced.
    */
    'id': number;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The name of the VCS Branch that was pushed
    */
    'name': string;
    /**
    * The URL from the provider of the VCS Branch that was pushed
    */
    'url': string;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionBranchPush.ActionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionBranchPush.ActionEnum"
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionBranchPush.attributeTypeMap;
    }
}

export namespace HistoryActionBranchPush {
    export enum ActionEnum {
        Push = <any> 'push'
    }
}
