/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An action representing a Task being created.
*/
export class HistoryActionTaskCreate {
    /**
    * The description of the Task.
    */
    'description': string;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * An array of Member IDs that represent who has been mentioned in the Task.
    */
    'mentionIds'?: Array<string>;
    /**
    * An array of Groups IDs that represent which have been mentioned in the Task.
    */
    'groupMentionIds'?: Array<string>;
    /**
    * An array of Member IDs that represent the Task\'s owners.
    */
    'ownerIds'?: Array<string>;
    /**
    * The ID of the entity referenced.
    */
    'id': number;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionTaskCreate.ActionEnum;
    /**
    * Whether or not the Task is complete.
    */
    'complete': boolean;
    /**
    * A timestamp that represent\'s the Task\'s deadline.
    */
    'deadline'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "mentionIds",
            "baseName": "mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "groupMentionIds",
            "baseName": "group_mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Array<string>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionTaskCreate.ActionEnum"
        },
        {
            "name": "complete",
            "baseName": "complete",
            "type": "boolean"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionTaskCreate.attributeTypeMap;
    }
}

export namespace HistoryActionTaskCreate {
    export enum ActionEnum {
        Create = <any> 'create'
    }
}
