/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An action representing a Task being deleted.
*/
export class HistoryActionTaskDelete {
    /**
    * The ID of the entity referenced.
    */
    'id': number;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The action of the entity referenced.
    */
    'action': HistoryActionTaskDelete.ActionEnum;
    /**
    * The description of the Task being deleted.
    */
    'description': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "HistoryActionTaskDelete.ActionEnum"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return HistoryActionTaskDelete.attributeTypeMap;
    }
}

export namespace HistoryActionTaskDelete {
    export enum ActionEnum {
        Delete = <any> 'delete'
    }
}
