/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A reference to a Story.
*/
export class HistoryReferenceStory {
    /**
    * The ID of the entity referenced.
    */
    'id': object;
    /**
    * The type of entity referenced.
    */
    'entityType': string;
    /**
    * The application URL of the Story.
    */
    'appUrl': string;
    /**
    * The name of the entity referenced.
    */
    'name': string;
    /**
    * If the referenced entity is a Story, either \"bug\", \"chore\", or \"feature\".
    */
    'storyType': HistoryReferenceStory.StoryTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "object"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "appUrl",
            "baseName": "app_url",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "storyType",
            "baseName": "story_type",
            "type": "HistoryReferenceStory.StoryTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return HistoryReferenceStory.attributeTypeMap;
    }
}

export namespace HistoryReferenceStory {
    export enum StoryTypeEnum {
        Feature = <any> 'feature',
        Chore = <any> 'chore',
        Bug = <any> 'bug'
    }
}
