/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Icons are used to attach images to Groups, Workspaces, Members, and Loading screens in the Shortcut web application.
*/
export class Icon {
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * The unique ID of the Icon.
    */
    'id': string;
    /**
    * The time/date that the Icon was created.
    */
    'createdAt': Date;
    /**
    * The time/date that the Icon was updated.
    */
    'updatedAt': Date;
    /**
    * The URL of the Icon.
    */
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Icon.attributeTypeMap;
    }
}

