/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class IterationAssociatedGroup {
    /**
    * The Group ID of the associated group.
    */
    'groupId': string;
    /**
    * The number of stories this Group owns in the Iteration.
    */
    'associatedStoriesCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string"
        },
        {
            "name": "associatedStoriesCount",
            "baseName": "associated_stories_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return IterationAssociatedGroup.attributeTypeMap;
    }
}

