/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { KeyResultValue } from './keyResultValue';

export class KeyResult {
    /**
    * The ID of the Key Result.
    */
    'id': string;
    /**
    * The name of the Key Result.
    */
    'name': string;
    /**
    * The Objective to which this Key Result belongs.
    */
    'objectiveId': number;
    /**
    * The type of the Key Result (numeric, percent, or boolean).
    */
    'type': KeyResult.TypeEnum;
    'initialObservedValue': KeyResultValue;
    'currentObservedValue': KeyResultValue;
    'currentTargetValue': KeyResultValue;
    /**
    * The integer percentage of progress toward completion of the Key Result.
    */
    'progress': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "objectiveId",
            "baseName": "objective_id",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "KeyResult.TypeEnum"
        },
        {
            "name": "initialObservedValue",
            "baseName": "initial_observed_value",
            "type": "KeyResultValue"
        },
        {
            "name": "currentObservedValue",
            "baseName": "current_observed_value",
            "type": "KeyResultValue"
        },
        {
            "name": "currentTargetValue",
            "baseName": "current_target_value",
            "type": "KeyResultValue"
        },
        {
            "name": "progress",
            "baseName": "progress",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return KeyResult.attributeTypeMap;
    }
}

export namespace KeyResult {
    export enum TypeEnum {
        Percent = <any> 'percent',
        Boolean = <any> 'boolean',
        Numeric = <any> 'numeric'
    }
}
