/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A group of calculated values for this Label. This is not included if the slim? flag is set to true for the List Labels endpoint.
*/
export class LabelStats {
    /**
    * The total number of Documents associated this Label.
    */
    'numRelatedDocuments': number;
    /**
    * The total number of Epics with this Label.
    */
    'numEpics': number;
    /**
    * The total number of stories unstarted Stories with this Label.
    */
    'numStoriesUnstarted': number;
    /**
    * The total number of Stories with this Label.
    */
    'numStoriesTotal': number;
    /**
    * The number of unstarted epics associated with this label.
    */
    'numEpicsUnstarted': number;
    /**
    * The number of in progress epics associated with this label.
    */
    'numEpicsInProgress': number;
    /**
    * The total number of unstarted points with this Label.
    */
    'numPointsUnstarted': number;
    /**
    * The total number of Stories with no point estimate with this Label.
    */
    'numStoriesUnestimated': number;
    /**
    * The total number of in-progress points with this Label.
    */
    'numPointsInProgress': number;
    /**
    * The total number of Epics associated with this Label.
    */
    'numEpicsTotal': number;
    /**
    * The total number of completed Stories with this Label.
    */
    'numStoriesCompleted': number;
    /**
    * The total number of completed points with this Label.
    */
    'numPointsCompleted': number;
    /**
    * The total number of stories backlog Stories with this Label.
    */
    'numStoriesBacklog': number;
    /**
    * The total number of points with this Label.
    */
    'numPointsTotal': number;
    /**
    * The total number of in-progress Stories with this Label.
    */
    'numStoriesInProgress': number;
    /**
    * The total number of backlog points with this Label.
    */
    'numPointsBacklog': number;
    /**
    * The number of completed Epics associated with this Label.
    */
    'numEpicsCompleted': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numRelatedDocuments",
            "baseName": "num_related_documents",
            "type": "number"
        },
        {
            "name": "numEpics",
            "baseName": "num_epics",
            "type": "number"
        },
        {
            "name": "numStoriesUnstarted",
            "baseName": "num_stories_unstarted",
            "type": "number"
        },
        {
            "name": "numStoriesTotal",
            "baseName": "num_stories_total",
            "type": "number"
        },
        {
            "name": "numEpicsUnstarted",
            "baseName": "num_epics_unstarted",
            "type": "number"
        },
        {
            "name": "numEpicsInProgress",
            "baseName": "num_epics_in_progress",
            "type": "number"
        },
        {
            "name": "numPointsUnstarted",
            "baseName": "num_points_unstarted",
            "type": "number"
        },
        {
            "name": "numStoriesUnestimated",
            "baseName": "num_stories_unestimated",
            "type": "number"
        },
        {
            "name": "numPointsInProgress",
            "baseName": "num_points_in_progress",
            "type": "number"
        },
        {
            "name": "numEpicsTotal",
            "baseName": "num_epics_total",
            "type": "number"
        },
        {
            "name": "numStoriesCompleted",
            "baseName": "num_stories_completed",
            "type": "number"
        },
        {
            "name": "numPointsCompleted",
            "baseName": "num_points_completed",
            "type": "number"
        },
        {
            "name": "numStoriesBacklog",
            "baseName": "num_stories_backlog",
            "type": "number"
        },
        {
            "name": "numPointsTotal",
            "baseName": "num_points_total",
            "type": "number"
        },
        {
            "name": "numStoriesInProgress",
            "baseName": "num_stories_in_progress",
            "type": "number"
        },
        {
            "name": "numPointsBacklog",
            "baseName": "num_points_backlog",
            "type": "number"
        },
        {
            "name": "numEpicsCompleted",
            "baseName": "num_epics_completed",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return LabelStats.attributeTypeMap;
    }
}

