/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Category } from './category';
import { MilestoneStats } from './milestoneStats';

/**
* (Deprecated) A Milestone is a collection of Epics that represent a release or some other large initiative that you are working on. Milestones have become Objectives, so you should use Objective-related API resources instead of Milestone ones.
*/
export class Milestone {
    /**
    * The Shortcut application url for the Milestone.
    */
    'appUrl': string;
    /**
    * The Milestone\'s description.
    */
    'description': string;
    /**
    * A boolean indicating whether the Milestone has been archived or not.
    */
    'archived': boolean;
    /**
    * A true/false boolean indicating if the Milestone has been started.
    */
    'started': boolean;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * A manual override for the time/date the Milestone was completed.
    */
    'completedAtOverride': Date | null;
    /**
    * The time/date the Milestone was started.
    */
    'startedAt': Date | null;
    /**
    * The time/date the Milestone was completed.
    */
    'completedAt': Date | null;
    /**
    * The name of the Milestone.
    */
    'name': string;
    'globalId': string;
    /**
    * A true/false boolean indicating if the Milestone has been completed.
    */
    'completed': boolean;
    /**
    * The workflow state that the Milestone is in.
    */
    'state': string;
    /**
    * A manual override for the time/date the Milestone was started.
    */
    'startedAtOverride': Date | null;
    /**
    * The time/date the Milestone was updated.
    */
    'updatedAt': Date;
    /**
    * An array of Categories attached to the Milestone.
    */
    'categories': Array<Category>;
    /**
    * The unique ID of the Milestone.
    */
    'id': number;
    /**
    * The IDs of the Key Results associated with the Objective.
    */
    'keyResultIds': Array<string>;
    /**
    * A number representing the position of the Milestone in relation to every other Milestone within the Workspace.
    */
    'position': number;
    'stats': MilestoneStats;
    /**
    * The time/date the Milestone was created.
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appUrl",
            "baseName": "app_url",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "started",
            "baseName": "started",
            "type": "boolean"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date"
        },
        {
            "name": "startedAt",
            "baseName": "started_at",
            "type": "Date"
        },
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "globalId",
            "baseName": "global_id",
            "type": "string"
        },
        {
            "name": "completed",
            "baseName": "completed",
            "type": "boolean"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<Category>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "keyResultIds",
            "baseName": "key_result_ids",
            "type": "Array<string>"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "MilestoneStats"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Milestone.attributeTypeMap;
    }
}

