/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ObjectiveSearchResult } from './objectiveSearchResult';

/**
* The results of the Objective search query.
*/
export class ObjectiveSearchResults {
    /**
    * The total number of matches for the search query. The first 1000 matches can be paged through via the API.
    */
    'total': number;
    /**
    * A list of search results.
    */
    'data': Array<ObjectiveSearchResult>;
    /**
    * The URL path and query string for the next page of search results.
    */
    'next': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ObjectiveSearchResult>"
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ObjectiveSearchResults.attributeTypeMap;
    }
}

