/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Category } from './category';
import { ObjectiveStats } from './objectiveStats';

/**
* An Objective is a collection of Epics that represent a release or some other large initiative that you are working on.
*/
export class Objective {
    /**
    * The Shortcut application url for the Objective.
    */
    'appUrl': string;
    /**
    * The Objective\'s description.
    */
    'description': string;
    /**
    * A boolean indicating whether the Objective has been archived or not.
    */
    'archived': boolean;
    /**
    * A true/false boolean indicating if the Objective has been started.
    */
    'started': boolean;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * A manual override for the time/date the Objective was completed.
    */
    'completedAtOverride': Date | null;
    /**
    * The time/date the Objective was started.
    */
    'startedAt': Date | null;
    /**
    * The time/date the Objective was completed.
    */
    'completedAt': Date | null;
    /**
    * The name of the Objective.
    */
    'name': string;
    'globalId': string;
    /**
    * A true/false boolean indicating if the Objectivehas been completed.
    */
    'completed': boolean;
    /**
    * The workflow state that the Objective is in.
    */
    'state': string;
    /**
    * A manual override for the time/date the Objective was started.
    */
    'startedAtOverride': Date | null;
    /**
    * The time/date the Objective was updated.
    */
    'updatedAt': Date;
    /**
    * An array of Categories attached to the Objective.
    */
    'categories': Array<Category>;
    /**
    * The unique ID of the Objective.
    */
    'id': number;
    /**
    * The IDs of the Key Results associated with the Objective.
    */
    'keyResultIds': Array<string>;
    /**
    * A number representing the position of the Objective in relation to every other Objective within the Workspace.
    */
    'position': number;
    'stats': ObjectiveStats;
    /**
    * The time/date the Objective was created.
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appUrl",
            "baseName": "app_url",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "started",
            "baseName": "started",
            "type": "boolean"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date"
        },
        {
            "name": "startedAt",
            "baseName": "started_at",
            "type": "Date"
        },
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "globalId",
            "baseName": "global_id",
            "type": "string"
        },
        {
            "name": "completed",
            "baseName": "completed",
            "type": "boolean"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<Category>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "keyResultIds",
            "baseName": "key_result_ids",
            "type": "Array<string>"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "ObjectiveStats"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Objective.attributeTypeMap;
    }
}

