/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RemoveCustomFieldParams {
    /**
    * The unique public ID for the CustomField.
    */
    'fieldId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fieldId",
            "baseName": "field_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RemoveCustomFieldParams.attributeTypeMap;
    }
}

