/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Repository refers to a VCS repository.
*/
export class Repository {
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * The shorthand name of the VCS repository.
    */
    'name': string | null;
    /**
    * The VCS provider for the Repository.
    */
    'type': Repository.TypeEnum;
    /**
    * The time/date the Repository was updated.
    */
    'updatedAt': Date | null;
    /**
    * The VCS unique identifier for the Repository.
    */
    'externalId': string | null;
    /**
    * The ID associated to the VCS repository in Shortcut.
    */
    'id': number | null;
    /**
    * The URL of the Repository.
    */
    'url': string | null;
    /**
    * The full name of the VCS repository.
    */
    'fullName': string | null;
    /**
    * The time/date the Repository was created.
    */
    'createdAt': Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Repository.TypeEnum"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "fullName",
            "baseName": "full_name",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Repository.attributeTypeMap;
    }
}

export namespace Repository {
    export enum TypeEnum {
        Github = <any> 'github',
        Gitlab = <any> 'gitlab',
        Bitbucket = <any> 'bitbucket'
    }
}
