/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The estimate value for the Story
*/
export class StoryHistoryChangeOldNewInt {
    /**
    * The old value.
    */
    'old'?: number;
    /**
    * The new value.
    */
    '_new'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "old",
            "baseName": "old",
            "type": "number"
        },
        {
            "name": "_new",
            "baseName": "new",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return StoryHistoryChangeOldNewInt.attributeTypeMap;
    }
}

