/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Task IDs that have been added or removed from the Story.
*/
export class StoryHistoryChangeAddsRemovesInt {
    /**
    * The values that have been added.
    */
    'adds'?: Array<number>;
    /**
    * The values that have been removed
    */
    'removes'?: Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "adds",
            "baseName": "adds",
            "type": "Array<number>"
        },
        {
            "name": "removes",
            "baseName": "removes",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return StoryHistoryChangeAddsRemovesInt.attributeTypeMap;
    }
}

