/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Emoji reaction on a comment.
*/
export class StoryReaction {
    /**
    * Emoji text of the reaction.
    */
    'emoji': string;
    /**
    * Permissions who have reacted with this.
    */
    'permissionIds': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emoji",
            "baseName": "emoji",
            "type": "string"
        },
        {
            "name": "permissionIds",
            "baseName": "permission_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return StoryReaction.attributeTypeMap;
    }
}

