/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StoryCustomField {
    /**
    * The unique public ID for a CustomField.
    */
    'fieldId': string;
    /**
    * The unique public ID for a CustomFieldEnumValue.
    */
    'valueId': string;
    /**
    * A string representation of the value, if applicable.
    */
    'value': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "fieldId",
            "baseName": "field_id",
            "type": "string"
        },
        {
            "name": "valueId",
            "baseName": "value_id",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StoryCustomField.attributeTypeMap;
    }
}

