/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A Task on a Story.
*/
export class Task {
    /**
    * Full text of the Task.
    */
    'description': string;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * The unique identifier of the parent Story.
    */
    'storyId': number;
    /**
    * `Deprecated:` use `member_mention_ids`.
    */
    'mentionIds': Array<string>;
    /**
    * An array of UUIDs of Members mentioned in this Task.
    */
    'memberMentionIds': Array<string>;
    /**
    * The time/date the Task was completed.
    */
    'completedAt': Date | null;
    /**
    * The time/date the Task was updated.
    */
    'updatedAt': Date | null;
    /**
    * An array of UUIDs of Groups mentioned in this Task.
    */
    'groupMentionIds': Array<string>;
    /**
    * An array of UUIDs of the Owners of this Task.
    */
    'ownerIds': Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the Task has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId': string | null;
    /**
    * The unique ID of the Task.
    */
    'id': number;
    /**
    * The number corresponding to the Task\'s position within a list of Tasks on a Story.
    */
    'position': number;
    /**
    * True/false boolean indicating whether the Task has been completed.
    */
    'complete': boolean;
    /**
    * The time/date the Task was created.
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "storyId",
            "baseName": "story_id",
            "type": "number"
        },
        {
            "name": "mentionIds",
            "baseName": "mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "memberMentionIds",
            "baseName": "member_mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "Date"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "groupMentionIds",
            "baseName": "group_mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Array<string>"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "position",
            "baseName": "position",
            "type": "number"
        },
        {
            "name": "complete",
            "baseName": "complete",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Task.attributeTypeMap;
    }
}

