/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Comments associated with Epic Discussions.
*/
export class ThreadedComment {
    /**
    * The Shortcut application url for the Comment.
    */
    'appUrl': string;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * True/false boolean indicating whether the Comment is deleted.
    */
    'deleted': boolean;
    /**
    * `Deprecated:` use `member_mention_ids`.
    */
    'mentionIds': Array<string>;
    /**
    * The unique ID of the Member that authored the Comment.
    */
    'authorId': string;
    /**
    * An array of Member IDs that have been mentioned in this Comment.
    */
    'memberMentionIds': Array<string>;
    /**
    * A nested array of threaded comments.
    */
    'comments': Array<ThreadedComment>;
    /**
    * The time/date the Comment was updated.
    */
    'updatedAt': Date;
    /**
    * An array of Group IDs that have been mentioned in this Comment.
    */
    'groupMentionIds': Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the Comment has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId': string | null;
    /**
    * The unique ID of the Comment.
    */
    'id': number;
    /**
    * The time/date the Comment was created.
    */
    'createdAt': Date;
    /**
    * The text of the Comment.
    */
    'text': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appUrl",
            "baseName": "app_url",
            "type": "string"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "mentionIds",
            "baseName": "mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "authorId",
            "baseName": "author_id",
            "type": "string"
        },
        {
            "name": "memberMentionIds",
            "baseName": "member_mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "comments",
            "baseName": "comments",
            "type": "Array<ThreadedComment>"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "groupMentionIds",
            "baseName": "group_mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ThreadedComment.attributeTypeMap;
    }
}

