/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The type of Story Link. The string can be subject or object. 
*/
export class TypedStoryLink {
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * The ID of the object Story.
    */
    'objectId': number;
    /**
    * How the subject Story acts on the object Story. This can be \"blocks\", \"duplicates\", or \"relates to\".
    */
    'verb': string;
    /**
    * This indicates whether the Story is the subject or object in the Story Link.
    */
    'type': string;
    /**
    * The time/date when the Story Link was last updated.
    */
    'updatedAt': Date;
    /**
    * The unique identifier of the Story Link.
    */
    'id': number;
    /**
    * The ID of the subject Story.
    */
    'subjectId': number;
    /**
    * The workflow state of the \"subject\" story.
    */
    'subjectWorkflowStateId': number;
    /**
    * The time/date when the Story Link was created.
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "objectId",
            "baseName": "object_id",
            "type": "number"
        },
        {
            "name": "verb",
            "baseName": "verb",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "subjectId",
            "baseName": "subject_id",
            "type": "number"
        },
        {
            "name": "subjectWorkflowStateId",
            "baseName": "subject_workflow_state_id",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return TypedStoryLink.attributeTypeMap;
    }
}

