/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateProject {
    /**
    * The Project\'s description.
    */
    'description'?: string;
    /**
    * A true/false boolean indicating whether the Story is in archived state.
    */
    'archived'?: boolean;
    /**
    * The number of days before the thermometer appears in the Story summary.
    */
    'daysToThermometer'?: number;
    /**
    * The color that represents the Project in the UI.
    */
    'color'?: string;
    /**
    * The Project\'s name.
    */
    'name'?: string;
    /**
    * An array of UUIDs for any Members you want to add as Followers.
    */
    'followerIds'?: Array<string>;
    /**
    * Configuration to enable or disable thermometers in the Story summary.
    */
    'showThermometer'?: boolean;
    /**
    * The ID of the team the project belongs to.
    */
    'teamId'?: number;
    /**
    * The Project abbreviation used in Story summaries. Should be kept to 3 characters at most.
    */
    'abbreviation'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "daysToThermometer",
            "baseName": "days_to_thermometer",
            "type": "number"
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Array<string>"
        },
        {
            "name": "showThermometer",
            "baseName": "show_thermometer",
            "type": "boolean"
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number"
        },
        {
            "name": "abbreviation",
            "baseName": "abbreviation",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateProject.attributeTypeMap;
    }
}

