/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateCategoryParams } from './createCategoryParams';

export class UpdateObjective {
    /**
    * The Objective\'s description.
    */
    'description'?: string;
    /**
    * A boolean indicating whether the Objective is archived or not
    */
    'archived'?: boolean;
    /**
    * A manual override for the time/date the Objective was completed.
    */
    'completedAtOverride'?: Date | null;
    /**
    * The name of the Objective.
    */
    'name'?: string;
    /**
    * The workflow state that the Objective is in.
    */
    'state'?: UpdateObjective.StateEnum;
    /**
    * A manual override for the time/date the Objective was started.
    */
    'startedAtOverride'?: Date | null;
    /**
    * An array of IDs of Categories attached to the Objective.
    */
    'categories'?: Array<CreateCategoryParams>;
    /**
    * The ID of the Objective we want to move this Objective before.
    */
    'beforeId'?: number;
    /**
    * The ID of the Objective we want to move this Objective after.
    */
    'afterId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "UpdateObjective.StateEnum"
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<CreateCategoryParams>"
        },
        {
            "name": "beforeId",
            "baseName": "before_id",
            "type": "number"
        },
        {
            "name": "afterId",
            "baseName": "after_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpdateObjective.attributeTypeMap;
    }
}

export namespace UpdateObjective {
    export enum StateEnum {
        InProgress = <any> 'in progress',
        ToDo = <any> 'to do',
        Done = <any> 'done'
    }
}
