/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { KeyResultValue } from './keyResultValue';

export class UpdateKeyResult {
    /**
    * The name of the Key Result.
    */
    'name'?: string;
    'initialObservedValue'?: KeyResultValue;
    'observedValue'?: KeyResultValue;
    'targetValue'?: KeyResultValue;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "initialObservedValue",
            "baseName": "initial_observed_value",
            "type": "KeyResultValue"
        },
        {
            "name": "observedValue",
            "baseName": "observed_value",
            "type": "KeyResultValue"
        },
        {
            "name": "targetValue",
            "baseName": "target_value",
            "type": "KeyResultValue"
        }    ];

    static getAttributeTypeMap() {
        return UpdateKeyResult.attributeTypeMap;
    }
}

