/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateCustomFieldEnumValue {
    /**
    * The unique ID of an existing EnumValue within the CustomField\'s domain.
    */
    'id'?: string;
    /**
    * A string value within the domain of this Custom Field.
    */
    'value'?: string;
    /**
    * A color key associated with this EnumValue within the CustomField\'s domain.
    */
    'colorKey'?: string | null;
    /**
    * Whether this EnumValue is enabled for its CustomField or not. Leaving this key out of the request leaves the current enabled state untouched.
    */
    'enabled'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "colorKey",
            "baseName": "color_key",
            "type": "string"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UpdateCustomFieldEnumValue.attributeTypeMap;
    }
}

