/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateStoryContents } from './updateStoryContents';

/**
* Request parameters for changing either a template\'s name or any of   the attributes it is designed to pre-populate.
*/
export class UpdateEntityTemplate {
    /**
    * The updated template name.
    */
    'name'?: string;
    'storyContents'?: UpdateStoryContents;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "storyContents",
            "baseName": "story_contents",
            "type": "UpdateStoryContents"
        }    ];

    static getAttributeTypeMap() {
        return UpdateEntityTemplate.attributeTypeMap;
    }
}

