/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateLabelParams } from './createLabelParams';

export class UpdateEpic {
    /**
    * The Epic\'s description.
    */
    'description'?: string;
    /**
    * A true/false boolean indicating whether the Epic is in archived state.
    */
    'archived'?: boolean;
    /**
    * An array of Labels attached to the Epic.
    */
    'labels'?: Array<CreateLabelParams>;
    /**
    * A manual override for the time/date the Epic was completed.
    */
    'completedAtOverride'?: Date | null;
    /**
    * An array of IDs for Objectives to which this Epic is related.
    */
    'objectiveIds'?: Array<number>;
    /**
    * The Epic\'s name.
    */
    'name'?: string;
    /**
    * The Epic\'s planned start date.
    */
    'plannedStartDate'?: Date | null;
    /**
    * `Deprecated` The Epic\'s state (to do, in progress, or done); will be ignored when `epic_state_id` is set.
    */
    'state'?: UpdateEpic.StateEnum;
    /**
    * `Deprecated` The ID of the Milestone this Epic is related to. Use `objective_ids`.
    */
    'milestoneId'?: number | null;
    /**
    * The ID of the member that requested the epic.
    */
    'requestedById'?: string;
    /**
    * The ID of the Epic State.
    */
    'epicStateId'?: number;
    /**
    * A manual override for the time/date the Epic was started.
    */
    'startedAtOverride'?: Date | null;
    /**
    * `Deprecated` The ID of the group to associate with the epic. Use `group_ids`.
    */
    'groupId'?: string | null;
    /**
    * An array of UUIDs for any Members you want to add as Followers on this Epic.
    */
    'followerIds'?: Array<string>;
    /**
    * An array of UUIDS for Groups to which this Epic is related.
    */
    'groupIds'?: Array<string>;
    /**
    * An array of UUIDs for any members you want to add as Owners on this Epic.
    */
    'ownerIds'?: Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the Epic has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId'?: string;
    /**
    * The ID of the Epic we want to move this Epic before.
    */
    'beforeId'?: number;
    /**
    * The ID of the Epic we want to move this Epic after.
    */
    'afterId'?: number;
    /**
    * The Epic\'s deadline.
    */
    'deadline'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<CreateLabelParams>"
        },
        {
            "name": "completedAtOverride",
            "baseName": "completed_at_override",
            "type": "Date"
        },
        {
            "name": "objectiveIds",
            "baseName": "objective_ids",
            "type": "Array<number>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "plannedStartDate",
            "baseName": "planned_start_date",
            "type": "Date"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "UpdateEpic.StateEnum"
        },
        {
            "name": "milestoneId",
            "baseName": "milestone_id",
            "type": "number"
        },
        {
            "name": "requestedById",
            "baseName": "requested_by_id",
            "type": "string"
        },
        {
            "name": "epicStateId",
            "baseName": "epic_state_id",
            "type": "number"
        },
        {
            "name": "startedAtOverride",
            "baseName": "started_at_override",
            "type": "Date"
        },
        {
            "name": "groupId",
            "baseName": "group_id",
            "type": "string"
        },
        {
            "name": "followerIds",
            "baseName": "follower_ids",
            "type": "Array<string>"
        },
        {
            "name": "groupIds",
            "baseName": "group_ids",
            "type": "Array<string>"
        },
        {
            "name": "ownerIds",
            "baseName": "owner_ids",
            "type": "Array<string>"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "beforeId",
            "baseName": "before_id",
            "type": "number"
        },
        {
            "name": "afterId",
            "baseName": "after_id",
            "type": "number"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return UpdateEpic.attributeTypeMap;
    }
}

export namespace UpdateEpic {
    export enum StateEnum {
        InProgress = <any> 'in progress',
        ToDo = <any> 'to do',
        Done = <any> 'done'
    }
}
