/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateCustomFieldEnumValue } from './updateCustomFieldEnumValue';

export class UpdateCustomField {
    /**
    * Indicates whether the Field is enabled for the Workspace. Only enabled fields can be applied to Stories.
    */
    'enabled'?: boolean;
    /**
    * A collection of objects representing reporting periods for years.
    */
    'name'?: string;
    /**
    * A collection of EnumValue objects representing the values in the domain of some Custom Field.
    */
    'values'?: Array<UpdateCustomFieldEnumValue>;
    /**
    * A frontend-controlled string that represents the icon for this custom field.
    */
    'iconSetIdentifier'?: string;
    /**
    * A description of the purpose of this field.
    */
    'description'?: string;
    /**
    * The ID of the CustomField we want to move this CustomField before.
    */
    'beforeId'?: string;
    /**
    * The ID of the CustomField we want to move this CustomField after.
    */
    'afterId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<UpdateCustomFieldEnumValue>"
        },
        {
            "name": "iconSetIdentifier",
            "baseName": "icon_set_identifier",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "beforeId",
            "baseName": "before_id",
            "type": "string"
        },
        {
            "name": "afterId",
            "baseName": "after_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateCustomField.attributeTypeMap;
    }
}

