/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An UploadedFile is any document uploaded to your Shortcut Workspace. Files attached from a third-party service are different: see the Linked Files endpoint.
*/
export class UploadedFile {
    /**
    * The description of the file.
    */
    'description': string | null;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * The unique IDs of the Stories associated with this file.
    */
    'storyIds': Array<number>;
    /**
    * `Deprecated:` use `member_mention_ids`.
    */
    'mentionIds': Array<string>;
    /**
    * The unique IDs of the Members who are mentioned in the file description.
    */
    'memberMentionIds': Array<string>;
    /**
    * The optional User-specified name of the file.
    */
    'name': string;
    /**
    * The url where the thumbnail of the file can be found in Shortcut.
    */
    'thumbnailUrl': string | null;
    /**
    * The size of the file.
    */
    'size': number;
    /**
    * The unique ID of the Member who uploaded the file.
    */
    'uploaderId': string;
    /**
    * Free form string corresponding to a text or image file.
    */
    'contentType': string;
    /**
    * The time/date that the file was updated.
    */
    'updatedAt': Date | null;
    /**
    * The name assigned to the file in Shortcut upon upload.
    */
    'filename': string;
    /**
    * The unique IDs of the Groups who are mentioned in the file description.
    */
    'groupMentionIds': Array<string>;
    /**
    * This field can be set to another unique ID. In the case that the File has been imported from another tool, the ID in the other tool can be indicated here.
    */
    'externalId': string | null;
    /**
    * The unique ID for the file.
    */
    'id': number;
    /**
    * The URL for the file.
    */
    'url': string | null;
    /**
    * The time/date that the file was created.
    */
    'createdAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "storyIds",
            "baseName": "story_ids",
            "type": "Array<number>"
        },
        {
            "name": "mentionIds",
            "baseName": "mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "memberMentionIds",
            "baseName": "member_mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "thumbnailUrl",
            "baseName": "thumbnail_url",
            "type": "string"
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number"
        },
        {
            "name": "uploaderId",
            "baseName": "uploader_id",
            "type": "string"
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string"
        },
        {
            "name": "groupMentionIds",
            "baseName": "group_mention_ids",
            "type": "Array<string>"
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return UploadedFile.attributeTypeMap;
    }
}

