/**
 * Shortcut API
 * Shortcut API
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WorkflowState } from './workflowState';

/**
* Workflow is the array of defined Workflow States. Workflow can be queried using the API but must be updated in the Shortcut UI. 
*/
export class Workflow {
    /**
    * A description of the workflow.
    */
    'description': string;
    /**
    * A string description of this resource.
    */
    'entityType': string;
    /**
    * An array of IDs of projects within the Workflow.
    */
    'projectIds': Array<number>;
    /**
    * A map of the states in this Workflow.
    */
    'states': Array<WorkflowState>;
    /**
    * The name of the workflow.
    */
    'name': string;
    /**
    * The date the Workflow was updated.
    */
    'updatedAt': Date;
    /**
    * Indicates if an owner is automatically assigned when an unowned story is started.
    */
    'autoAssignOwner': boolean;
    /**
    * The unique ID of the Workflow.
    */
    'id': number;
    /**
    * The ID of the team the workflow belongs to.
    */
    'teamId': number;
    /**
    * The date the Workflow was created.
    */
    'createdAt': Date;
    /**
    * The unique ID of the default state that new Stories are entered into.
    */
    'defaultStateId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "entityType",
            "baseName": "entity_type",
            "type": "string"
        },
        {
            "name": "projectIds",
            "baseName": "project_ids",
            "type": "Array<number>"
        },
        {
            "name": "states",
            "baseName": "states",
            "type": "Array<WorkflowState>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date"
        },
        {
            "name": "autoAssignOwner",
            "baseName": "auto_assign_owner",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "teamId",
            "baseName": "team_id",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "defaultStateId",
            "baseName": "default_state_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Workflow.attributeTypeMap;
    }
}

